Repository canonical/lxd-ui, pull requests merged in 2023-04, with the labels that each got.

#267 Disable create button when an invalid name is entered [WD-1874]
  src/pages/instances/actions/snapshots/CreateSnapshotForm.tsx
Labels: Review: Code needed, Review: QA needed

#269 Remove unnecessary check for an always truthy payload in InstanceTerminal
  src/pages/instances/InstanceTerminal.tsx
Labels: Review: Code needed

#270 Use react-component's Icon consistently [WD-2712]
  src/components/EmptyState.tsx
  src/components/Navigation.tsx
  src/components/PanelHeader.tsx
  src/components/SubmitButton.tsx
  src/pages/certificates/CertificateGenerate.tsx
  src/pages/instances/InstanceDetailPanel.tsx
  src/pages/instances/InstanceStatusIcon.tsx
  src/pages/instances/actions/OpenTerminalBtn.tsx
Labels: Review: Code needed, Review: QA needed

#271 Limit CSS of actions-list to direct descendents
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#268 Add snapshot configuration WD-3026
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/actions/snapshots/ConfigureSnapshotModal.tsx
  src/pages/instances/actions/snapshots/ConfigureSnapshotsBtn.tsx
  src/pages/instances/actions/snapshots/CreateSnapshotForm.tsx
  src/pages/instances/forms/ConfigurationTable.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/sass/_forms.scss
  src/sass/_instance_detail_snapshots.scss
  src/sass/styles.scss
  src/util/instanceEdit.tsx
  src/util/zIndex.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#273 Improve snapshots section in instance side panel [WD-2710]
  src/pages/instances/InstanceDetailPanel.tsx
  src/sass/_instance_detail_panel.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#278 Change copy to expiry
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/actions/snapshots/CreateSnapshotForm.tsx
  src/pages/instances/forms/SnapshotsForm.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#275 Add instance and profile renaming
  src/components/SubmitButton.tsx
  src/pages/instances/InstanceDetail.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/forms/InstanceEditDetailsForm.tsx
  src/pages/instances/forms/InstanceRename.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/pages/profiles/ProfileDetail.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/profiles/forms/ProfileRename.tsx
  src/pages/projects/EditProjectForm.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/projects/forms/ProjectForm.tsx
  src/sass/_instance_detail_page.scss
  src/sass/_profile_detail_page.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#283 Removed the instance count from the instance page header [WD-2937]
  src/pages/instances/InstanceList.tsx
  src/sass/_instance_list.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#284 Use capitalised labels for instance types [WD-2877]
  src/pages/images/ImageSelector.tsx
  src/pages/instances/InstanceList.tsx
  src/util/instanceOptions.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#288 Responsive snapshot list in instance detail page
  src/pages/instances/InstanceSnapshots.tsx
  src/sass/_instance_detail_snapshots.scss
  src/sass/_instance_list.scss
  src/sass/_selectable_main_table.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#290 Align table headings with navigation WD-2936
  src/pages/instances/InstanceList.tsx
  src/sass/_instance_list.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#294 Refactor names of confirm and cancel props for the ConfirmationButton
  src/components/ConfirmationButton.tsx
  src/components/ConfirmationModal.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/PauseInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/instances/actions/snapshots/SnapshotActions.tsx
  src/pages/instances/actions/snapshots/SnapshotBulkDelete.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storages/actions/DeleteStorageBtn.tsx
Labels: Review: Code +1

#289 Table sorting across multiple pages, sort snapshots by recency
  src/pages/cluster/ClusterList.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverviewNetworks.tsx
  src/pages/instances/InstanceOverviewProfiles.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/storages/StorageList.tsx
  src/pages/warnings/WarningList.tsx
  src/sass/_instance_detail_snapshots.scss
  src/sass/_instance_list.scss
  src/util/pagination.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#301 Ensure creation form sections are active, simplify section…
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/forms/FormMenuItem.tsx
  src/pages/instances/forms/ResourceLimitsForm.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/EditProfileForm.tsx
Labels: Review: Code +1, Review: QA +1

#303 Removed unneeded wrapper, improved readability of conditional rendering
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Maintenance 🔨

#309 Update profiles icon [WD-2911]
  src/components/Navigation.tsx
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#311 Add empty placeholder when there are no networks in the instance overview [WD-3317]
  src/pages/instances/InstanceOverviewNetworks.tsx
Labels: Review: Code +1, Review: QA +1

#313 Make default project and profile be always first in list [WD-3190]
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/ProfileSelector.tsx
  src/pages/projects/ProjectSelector.tsx
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#308 Add version in main navigation WD-3409
  src/components/Navigation.tsx
  src/components/ServerVersion.tsx
  src/sass/_pattern_navigation.scss
  src/types/server.d.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#310 Improve empty states of instances, networks, storages [WD-2915]
  src/pages/instances/InstanceConsole.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/storages/StorageList.tsx
  src/pages/storages/actions/AddStorageBtn.tsx
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#316 Fx some issues with a11y
  src/components/EmptyState.tsx
  src/components/SelectableMainTable.tsx
  src/pages/instances/InstanceSnapshots.tsx
Labels: Review: Code +1, Review: QA +1

#317 404 page overhaul [WD-3149]
  src/components/NoMatch.tsx
  src/sass/_no_match.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#315 Adjust styling of the authentication page WD-3436
  src/pages/certificates/BrowserImport.tsx
  src/pages/certificates/CertificateGenerate.tsx
  src/pages/certificates/CertificateMain.tsx
  src/sass/_certificates.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1
