Repository canonical/lxd-ui, pull requests merged in 2023-10, with the labels that each got.

#481 Ensure all forms submit when pressing enter on an input field
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/TerminalPayloadForm.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/pages/settings/SettingFormInput.tsx
  src/pages/settings/SettingFormPassword.tsx
  src/pages/storage/StoragePoolForm.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
Labels: Review: Code needed, Review: QA needed

#482 Use websocket to track long running operations
  src/api/instances.tsx
  src/context/eventQueue.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/AttachIsoBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/InstanceBulkActions.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/instances/actions/PauseInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/instances/actions/snapshots/ConfigureSnapshotModal.tsx
  src/sass/_instance_detail_snapshots.scss
  src/util/instanceStart.tsx
Labels: Review: Code +1, Review: QA +1

#486 Ensure instance count on the list is correct on creation of instances
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#475 Move instance list pagination and selection text above table
  src/components/Pagination.tsx
  src/components/SelectableMainTable.tsx
  src/components/SelectedTableNotification.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/sass/_cluster_group_form.scss
  src/sass/_instance_list.scss
  src/sass/_selectable_main_table.scss
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#492 feat(operations): add test for getProjectName [WD-6612]
  src/util/operations.spec.tsx
  src/util/operations.tsx
Labels: Review: Code +1

#483 Add documentation links to all main page headings WD-6525
  src/components/HelpLink.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/UploadCustomImageHint.tsx
  src/pages/warnings/WarningList.tsx
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#496 Sections of the edit network form get dedicated routes
  src/App.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/util/networkEdit.tsx
  tests/networks.spec.ts
Labels: Review: Code +1, Review: QA +1

#488 Ensure multiselect snapshots behaves the same as instances WD-6704
  src/pages/instances/InstanceSnapshots.tsx
  src/sass/_instance_detail_snapshots.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#499 Invalidate project cache
  src/pages/images/actions/DeleteCachedImageBtn.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/storage/actions/DeleteStorageVolumeBtn.tsx
  src/pages/storage/forms/StorageVolumeCreate.tsx
Labels: Review: Code +1, Review: QA +1

#500 Avoid busy fetching operations but rely on events websocket
  src/pages/instances/Events.tsx
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#502 Use base style for all cancel buttons
  src/pages/images/CustomIsoSelector.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/MigrateInstanceForm.tsx
  src/pages/instances/TerminalPayloadForm.tsx
  src/pages/instances/actions/snapshots/ConfigureSnapshotModal.tsx
  src/pages/instances/actions/snapshots/SnapshotForm.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/operations/OperationList.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/pages/projects/EditProjectForm.tsx
  src/pages/settings/SettingFormCheckbox.tsx
  src/pages/settings/SettingFormInput.tsx
  src/pages/settings/SettingFormPassword.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/forms/StorageVolumeEdit.tsx
Labels: Review: Code +1, Review: QA +1

#501 Add tests for custom volumes and networks
  src/components/forms/DiskDeviceFormCustom.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  tests/devices.spec.ts
  tests/helpers/devices.ts
  tests/helpers/profile.ts
Labels: Review: Code +1, Review: QA +1

#505 whitelist snapshot name characters
  src/util/snapshots.tsx
Labels: Review: Code needed, Review: QA needed

#508 Optimise usage of setLoading/setSubmitting functions
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/cluster/actions/DeleteClusterGroupBtn.tsx
  src/pages/cluster/actions/EvacuateClusterMemberBtn.tsx
  src/pages/cluster/actions/RestoreClusterMemberBtn.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/forms/StorageVolumeEdit.tsx
Labels: Review: Code +1, Review: QA +1

#506 Use events stream for all long-running operations [WD-6846]
  src/api/images.tsx
  src/api/instances.tsx
  src/api/operations.tsx
  src/api/projects.tsx
  src/api/snapshots.tsx
  src/api/storage-pools.tsx
  src/pages/images/actions/DeleteCachedImageBtn.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/actions/snapshots/CreateSnapshotForm.tsx
  src/pages/instances/actions/snapshots/EditSnapshot.tsx
  src/pages/instances/actions/snapshots/SnapshotActions.tsx
  src/pages/instances/actions/snapshots/SnapshotBulkDelete.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#504 Add storage pool and volume tests
  src/api/storage-pools.tsx
  src/context/useClusterMembers.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StoragePoolOverview.tsx
  src/util/helpers.tsx
  tests/devices.spec.ts
  tests/helpers/devices.ts
  tests/helpers/storagePool.ts
  tests/helpers/storageVolume.ts
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#509 Preserve full sub-path when switching projects
  src/pages/storage/Storage.tsx
  src/util/projects.tsx
Labels: Review: Code +1, Review: QA +1

#503 Boolean config options should have boolean default value
  public/assets/data/config-options.json
Labels: Review: Code +1, Review: QA +1

#511 Settings page: improved alignment, end-aligned edit icon in read mode [WD-6659]
  src/pages/settings/SettingForm.tsx
  src/pages/settings/Settings.tsx
  src/sass/_settings_page.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#510 Show size hidden columns in instance table column toggle
  src/components/TableColumnsSelect.tsx
  src/pages/instances/InstanceList.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#514 feat(tab-links): Refactor into new TabLinks component [WD-6842]
  src/components/TabLinks.tsx
  src/pages/instances/InstanceDetail.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/profiles/ProfileDetail.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StorageVolumeDetail.tsx
  src/util/projects.tsx
Labels: Review: Code +1, Review: QA +1

#515 Use web worker for certificate generation WD-6613
  src/pages/login/CertificateGenerate.tsx
  src/util/certificate.tsx
Labels: Review: Code +1, Review: QA +1
