Repository canonical/lxd-ui, pull requests merged in 2023-05, with the labels that each got.

#327 Fix storage cache key for detail page #325
  src/pages/storages/StorageDetail.tsx
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#330 Auto-focus for terminal and text console
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
Labels: Review: Code +1, Review: QA +1

#329 Improve tutorial for windows browsers #324
  src/pages/certificates/BrowserImport.tsx
  src/pages/certificates/CertificateGenerate.tsx
  src/sass/_certificates.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#336 Ask for certificate password on creation #331
  src/pages/certificates/CertificateGenerate.tsx
  src/pages/certificates/PasswordModal.tsx
  src/util/certificate.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#338 Simplify instance address displayal
  src/pages/instances/InstanceDetailPanel.tsx
  src/pages/instances/InstanceIps.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/networks/MapTooltip.tsx
  src/util/networks.tsx
Labels: Review: Code +1, Review: QA +1

#339 Add instance bulk deletion
  src/api/instances.tsx
  src/components/ConfirmationButton.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/sass/_instance_list.scss
  src/types/instance.d.ts
  src/util/instanceDelete.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#340 Deal with query strings in operation urls WD-3656
  src/api/operations.tsx
Labels: Review: Code +1, Review: QA +1

#344 Select 1st pool when configuring root storage
  src/pages/instances/forms/RootStorageForm.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#345 Configurable backend ip for dev mode WD-3856
  .env
  entrypoint
  haproxy-dev.cfg
Labels: Review: Code +1, Review: QA +1

#349 [README] Add steps to setup the development environment to run the LXD UI on a Mac [WD-3922]
  README.md
Labels: Review: Code +1, Review: QA +1

#346 Link to instance list with profile filter applied [WD-3874]
  src/pages/instances/InstanceSearchFilter.tsx
  src/pages/profiles/ProfileDetailPanel.tsx
  src/pages/profiles/ProfileInstances.tsx
  src/pages/profiles/ProfileUsedByDefaultProject.tsx
  src/pages/profiles/ProfileUsedByRegularProject.tsx
  src/pages/profiles/actions/ViewProfileInstancesBtn.tsx
  src/sass/_profile_used_by_default_project.scss
Labels: Review: Design +1, Review: Code +1

#350 Avoid table jumping on selecting / unselecting instances
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#352 fix(navigation): fix side navigation font weight [WD-3835]
  src/components/Navigation.tsx
Labels: Review: Code +1, Review: QA +1

#354 Avoid loading project when no project name is specified
  src/context/project.tsx
Labels: Review: Code +1, Review: QA +1

#359 Ensure image is always controlled component in creation form
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
Labels: Review: Code +1, Review: QA +1

#358 Ensure bulk actions have a key prop
  src/pages/instances/actions/InstanceBulkAction.tsx
Labels: Review: Code +1, Review: QA +1

#355 Add scrollable table component WD-3408
  src/components/Pagination.tsx
  src/components/ScrollableTable.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/forms/ConfigurationTable.tsx
  src/pages/profiles/ProfileList.tsx
  src/sass/_configuration_table.scss
  src/sass/_instance_detail_snapshots.scss
  src/sass/_instance_list.scss
  src/sass/_profile_list.scss
  src/sass/_scrollable_table.scss
  src/sass/styles.scss
  src/util/updateTBodyHeight.tsx
Labels: Review: Code +1, Review: QA +1

#361 Simplify notification clear
  src/context/notify.tsx
Labels: Review: Code needed

#353 fix(detailed pages): Make delete btns more visible on detail pages WD-3870
  src/context/useDeleteIcon.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/storage/StorageDetailHeader.tsx
  src/pages/storage/actions/DeleteStorageBtn.tsx
  src/sass/_instance_detail_page.scss
  src/sass/_profile_detail_page.scss
  src/sass/_rename_header.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1
