Repository canonical/lxd-ui, pull requests merged in 2023-07, with the labels that each got.

#403 Update link targets for docs and discuss
  src/components/Navigation.tsx
Labels: Review: Code needed, Review: QA needed

#407 Fix notification on instance creation and clear cache
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/InstanceList.tsx
  src/util/operations.tsx
Labels: Review: Code +1, Review: QA +1

#408 fix(pagination) avoid passing pagination props to div
  src/components/Pagination.tsx
Labels: Review: Code +1, Review: QA +1

#406 Update to vanilla 4.0 and adjust some styles
  package.json
  src/pages/instances/InstanceOverview.tsx
  src/pages/login/CertificateAdd.tsx
  src/pages/login/CertificateGenerate.tsx
  src/pages/profiles/ProfileDetailOverview.tsx
  src/sass/_cluster_list.scss
  src/sass/styles.scss
  yarn.lock
Labels: Review: Design needed, Review: Code +1, Review: QA needed

#414 Update broken reference in PR template
  .github/pull_request_template.md
Labels: Review: Code needed, Maintenance 🔨

#424 fix instance and profile editing with custom networks applied
  src/pages/instances/forms/NetworkForm.tsx
  src/util/formDevices.tsx
Labels: Review: Code needed, Review: QA needed

#421 Use absolute as default for memory input, adjust labels WD-5100
  src/pages/instances/forms/CpuLimitSelector.tsx
  src/pages/instances/forms/MemoryLimitSelector.tsx
  src/util/defaults.tsx
  src/util/limits.tsx
  tests/helpers/configuration.ts
  tests/instances.spec.ts
  tests/profiles.spec.ts
Labels: Review: Code needed, Review: QA needed
