Repository canonical/lxd-ui, pull requests merged in 2023-12, with the labels that each got.

#507 Add validation on instance create
  .github/workflows/commits.yaml
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/components/forms/FormMenuItem.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/sass/_forms.scss
  src/util/formDevices.tsx
  src/util/instanceValidation.tsx
  tests/devices.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#544 Submit in custom disk device creation modal improvements
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#564 Project details form: move notification row out of scrollable area
  src/pages/projects/forms/ProjectForm.tsx
  src/sass/_forms.scss
Labels: Review: Code +1, Review: QA +1, Maintenance 🔨

#565 All pr workflows in a single group
  .github/workflows/commits.yaml
  .github/workflows/pr.yaml
Labels: Review: Code +1

#571 Do not pass dynamicHeight as DOM attribute to textarea
  src/components/AutoExpandingTextArea.tsx
Labels: Review: Code +1, Review: QA +1

#576 chore(tests) add tests for server configs [WD-7703]
  tests/helpers/server.ts
  tests/server.spec.ts
Labels: Review: Code +1

#578 fix(app) disable configurations when entity creation is blocked [WD-7489]
  src/pages/instances/CreateInstance.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/storage/forms/StorageVolumeFormMenu.tsx
Labels: Review: Design needed, Review: Code needed, Review: QA needed

#573 feat(storage) default storage pool for volume creation [WD-7675]
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/actions/CreateVolumeBtn.tsx
  src/pages/storage/forms/StorageVolumeCreate.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#579 chore: publish test reports to github pages [WD-7907]
  .github/workflows/delete_test_reports.yml
  .github/workflows/pr.yaml
Labels: Review: Code +1

#584 fix(actions): github actions for test report publishig failing
  .github/workflows/delete_test_reports.yml
  .github/workflows/pr.yaml
Labels: Review: Code needed

#585 chore: clean up test report publish gh action
  .github/workflows/cla_check.yml
  .github/workflows/delete_test_reports.yml
  .github/workflows/pr.yaml
Labels: Review: Code needed
