Repository canonical/lxd-ui, pull requests merged in 2023-06, with the labels that each got.

#360 Ensure instances are started after creation even with long running create processes WD-4050
  src/api/instances.tsx
  src/context/eventQueue.tsx
  src/index.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/InstanceStatusIcon.tsx
  src/types/event.d.ts
Labels: Review: Code +1, Review: QA +1

#364 fix(instances) connect events websocket to all projects WD-4353
  src/pages/instances/Events.tsx
Labels: Review: Code +1, Review: QA +1

#367 Keep table headers sticky in the image selection modal [WD-4289]
  src/components/ScrollableTable.tsx
  src/pages/images/ImageSelector.tsx
  src/sass/_forms.scss
  src/util/helpers.tsx
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#373 fix(loader): fix loading state on smaller devices WD-4197
  src/App.tsx
Labels: Review: Code +1, Review: QA +1

#368 feat(cert) add certificate generation for macOS WD-4079 #331
  src/pages/certificates/BrowserImport.tsx
  src/pages/certificates/CertificateGenerate.tsx
  src/pages/certificates/PasswordModal.tsx
  src/util/certificate.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#369 Target cluster group or member on instance creation WD-4263
  src/api/instances.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/instances/forms/InstanceLocationSelect.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#374 Allow certificate adding with tokens WD-4251 #343
  src/App.tsx
  src/api/certificates.tsx
  src/components/Navigation.tsx
  src/pages/certificates/CertificateAdd.tsx
  src/pages/certificates/CertificateAddForm.tsx
  src/pages/certificates/CertificateMain.tsx
Labels: Review: Code +1, Review: QA +1

#375 Keep items bottom-aligned when not authenticated
  src/components/Navigation.tsx
  src/sass/_pattern_navigation.scss
Labels: Review: Code needed, Review: QA needed

#371 fix(operations) ensure instance parsing is compatible with future urls
  src/util/operations.tsx
Labels: Review: Code +1, Review: QA +1

#376 Avoid navigation open/close on first paint, avoid closing menu on resize for mobile
  src/context/menuCollapsed.tsx
Labels: Review: Code +1, Review: QA +1

#378 Move cluster empty states out of the table
  src/pages/cluster/ClusterList.tsx
Labels: Review: Code needed, Review: QA needed

#383 Add shortcuts for common keyboard combinations #381
  src/lib/spice/src/inputs.js
  src/pages/instances/InstanceConsole.tsx
Labels: Review: Code needed, Review: QA needed

#384 Design fixes for the settings form in read mode
  src/pages/settings/SettingForm.tsx
  src/sass/_settings_page.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#380 Allow login with oidc WD-4314
  haproxy-dev.cfg
  public/assets/data/config-options.json
  src/App.tsx
  src/components/BaseLayout.tsx
  src/components/Navigation.tsx
  src/components/ProtectedRoute.tsx
  src/pages/certificates/CertificateMain.tsx
  src/pages/login/BrowserImport.tsx
  src/pages/login/CertificateAdd.tsx
  src/pages/login/CertificateAddForm.tsx
  src/pages/login/CertificateGenerate.tsx
  src/pages/login/Login.tsx
  src/pages/login/PasswordModal.tsx
  src/sass/_pattern_navigation.scss
  src/sass/styles.scss
  src/types/server.d.ts
  src/util/cookies.tsx
Labels: Review: Code needed, Review: QA needed

#385 Remove unused NetworkSelector component
  src/pages/networks/NetworkSelector.tsx
Labels: Review: Code needed

#387 Replace old prop name with new prop name (confirmExtra)
  src/pages/instances/actions/snapshots/SnapshotActions.tsx
Labels: Review: Code needed

#388 Replace ambiguous modal button labels
  src/components/ConfirmationButton.tsx
  src/components/ConfirmationModal.tsx
  src/pages/operations/actions/CancelOperationBtn.tsx
Labels: Review: Code needed, Review: QA needed

#390 Invalidate operations query upon operation cancellation
  src/pages/instances/InstanceList.tsx
  src/pages/operations/OperationList.tsx
  src/pages/operations/actions/CancelOperationBtn.tsx
Labels: Review: Code needed, Review: QA needed

#391 Add hacking.md and update screenshots in readme
  HACKING.md
  README.md
Labels: Review: Code +1

#392 fix side nav spacing on small height WD-4524
  src/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#394 Remove external link class
  src/pages/cluster/ClusterList.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/forms/SnapshotsForm.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/storage/StorageList.tsx
Labels: Review: Code needed

#398 Auto-logout on token issue (expired/invalid refresh token)
  src/components/Navigation.tsx
  src/util/helpers.tsx
Labels: Review: Code needed, Review: QA needed

#399 Use PS5 registry
  konf/site.yaml
Labels: Review: Code needed
