Repository canonical/lxd-ui, pull requests merged in 2023-02, with the labels that each got.

#184 Add start page for unauthenticated user and adapt nav menu [WD-1348]
  haproxy-demo.cfg
  static/js/App.tsx
  static/js/api/certificates.tsx
  static/js/components/Navigation.tsx
  static/js/components/ProtectedRoute.tsx
  static/js/context/auth.tsx
  static/js/index.tsx
  static/js/pages/certificates/CertificateGenerate.tsx
  static/js/pages/certificates/CertificateMain.tsx
  static/js/pages/instances/CreateInstanceForm.tsx
  static/js/pages/instances/InstanceDetailPanel.tsx
  static/js/pages/instances/InstanceList.tsx
  static/js/pages/instances/InstanceOverview.tsx
  static/js/pages/profiles/ProfileDetail.tsx
  static/js/pages/profiles/ProfileList.tsx
  static/js/util/queryKeys.tsx
  static/sass/_breakpoints.scss
  static/sass/styles.scss
  webpack.config.js
Labels: Review: Design +1, Review Code +1

#186 wrap cert main page in a l-main container to fix layout for mobile
  static/js/pages/certificates/CertificateMain.tsx
Labels: Review: Code needed

#190 Overhaul instance list header [WD-1892]
  static/js/pages/instances/CreateInstanceForm.tsx
  static/js/pages/instances/InstanceList.tsx
  static/js/util/instanceOptions.tsx
  static/sass/_instance_list.scss
  static/sass/_settings.scss
Labels: Review: Design +1, Review Code +1

#191 Configurable columns on instance table
  static/js/components/TableColumnsSelect.tsx
  static/js/pages/instances/InstanceList.tsx
  static/sass/_instance_list.scss
Labels: Review: Design +1, Review Code +1

#197 Adjust empty state of instance list page [WD-1957]
  static/js/components/EmptyState.tsx
  static/js/pages/instances/InstanceList.tsx
  static/sass/_empty_state.scss
  static/sass/_instance_list.scss
  static/sass/_settings.scss
  static/sass/styles.scss
Labels: Review: Code needed

#207 Headings in profile and instance details should be muted
  static/js/pages/instances/InstanceOverview.tsx
  static/js/pages/profiles/ProfileDetail.tsx
Labels: Review: Design +1, Review Code +1

#211 Instance create notify WD-1964
  static/js/api/instances.tsx
  static/js/components/NotificationRow.tsx
  static/js/pages/instances/CreateInstanceForm.tsx
  static/js/types/notification.d.ts
  static/js/util/useNotification.tsx
Labels: Review: Code needed, Review: Design +1

#208 Add network map WD-2133
  package.json
  static/js/App.tsx
  static/js/pages/networks/MapLegend.tsx
  static/js/pages/networks/MapTooltip.tsx
  static/js/pages/networks/NetworkList.tsx
  static/js/pages/networks/NetworkMap.tsx
  static/sass/_network_map.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Design needed, Review: Code needed, Review: Design +1
