Repository canonical/lxd-ui, pull requests merged in 2023-11, with the labels that each got.

#519 Replace pause with freeze throughout the app [WD-6701]
  src/context/instanceLoading.tsx
  src/pages/instances/actions/FreezeInstanceBtn.tsx
  src/pages/instances/actions/InstanceBulkAction.tsx
  src/pages/instances/actions/InstanceBulkActions.tsx
  src/pages/instances/actions/InstanceStateActions.tsx
  src/util/instanceBulkActions.tsx
Labels: Review: Code needed, Review: QA needed

#512 Retry for network changes on localhost
  src/api/networks.tsx
  src/types/network.d.ts
  src/util/networks.spec.tsx
  src/util/networks.tsx
Labels: Review: Code +1

#518 Ensure correct type is set when creating an instance from a cached image
  src/pages/images/CachedImageList.tsx
  src/pages/images/CustomIsoModal.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/images/actions/CreateInstanceFromImageBtn.tsx
  src/pages/images/actions/SelectImageBtn.tsx
  src/pages/images/actions/UseCustomIsoBtn.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/types/image.d.ts
Labels: Review: Code +1, Review: QA +1

#513 Ensure clustered backend pools are created and not left in pending state
  src/api/storage-pools.tsx
  src/pages/storage/StoragePools.tsx
  tests/helpers/storagePool.ts
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#527 Change instance filtering to url instead of state [WD-7026]
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSearchFilter.tsx
Labels: Review: Code +1, Review: QA +1

#517 Copy update: password is not necessarily empty
  src/pages/login/BrowserImport.tsx
Labels: Review: Design +1, Review: Code +1

#516 Reduce font size of the text in the cluster group selector
  src/sass/_cluster_list.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#534 README: Pass the `--channel` argument to `snap refresh`, not only `--stable`
  README.md
Labels: Documentation 📝, Review: Code +1

#522 Move image list to top level
  src/App.tsx
  src/components/Navigation.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/Images.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/pages/storage/Storage.tsx
  src/sass/_images.scss
  src/sass/_storage.scss
  src/sass/styles.scss
  src/util/images.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#533 Link to local docs
  haproxy-demo.cfg
  haproxy-dev.cfg
  src/components/Navigation.tsx
  src/components/forms/SnapshotsForm.tsx
  src/context/useDocs.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/forms/StorageVolumeFormSnapshots.tsx
  src/pages/warnings/WarningList.tsx
  tests/helpers/network.ts
Labels: Review: Code +1, Review: QA +1

#538 Add local docs for images page
  src/pages/images/Images.tsx
Labels: Review: Code needed, Review: QA needed

#536 Use regular link from profile detail to instances with that profile
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSearchFilter.tsx
  src/pages/profiles/ProfileUsedByDefaultProject.tsx
  src/pages/profiles/ProfileUsedByRegularProject.tsx
  src/pages/profiles/actions/ViewProfileInstancesBtn.tsx
  src/pages/profiles/actions/ViewProfileInstancesLink.tsx
Labels: Review: Code +1, Review: QA +1

#539 Show "Never" when instance has never been used
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#540 Avoid conflict between filters and side panel params
  src/pages/instances/InstanceSearchFilter.tsx
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#529 Improve networking
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/networks/forms/NetworkSelector.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/types/network.d.ts
  src/util/instanceConfigInheritance.tsx
  src/util/networkEdit.tsx
  src/util/networks.tsx
  src/util/settings.tsx
  tests/networks.spec.ts
Labels: Review: Code +1, Review: QA +1

#541 Show interface name next to ip addresses WD-7270
  src/pages/instances/InstanceIps.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/networks/MapTooltip.tsx
  src/util/networks.tsx
Labels: Review: Code needed, Review: QA needed

#535 Improve storage
  src/components/TabLinks.tsx
  src/pages/instances/InstanceSearchFilter.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StoragePoolHeader.tsx
  src/pages/storage/StorageVolumeOverview.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/StorageVolumesFilter.tsx
  src/pages/storage/actions/DeleteStorageVolumeBtn.tsx
  src/pages/storage/actions/StorageVolumesInPoolBtn.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/helpers.tsx
  src/util/searchAndFilter.spec.tsx
  src/util/searchAndFilter.tsx
  src/util/storageVolume.tsx
Labels: Review: Code +1, Review: QA +1

#555 Make snapshot name optional
  src/pages/instances/actions/snapshots/SnapshotForm.tsx
  src/util/snapshots.tsx
Labels: Review: Code needed, Review: QA needed

#553 Fix keyboard mappings in graphic console
  src/lib/spice/src/code_to_scancode.js
  src/lib/spice/src/spicemsg.js
  src/lib/spice/src/utils.js
Labels: Review: Code +1, Review: QA +1

#556 Require signed commits
  .github/workflows/commits.yaml
Labels: Review: Code +1, Review: QA +1

#547 Fix terminal newlines
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
Labels: Review: Code +1, Review: QA +1

#557 Ensure new creating instances are shown consistently during creation
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#558 fix(instance) changed to better wording for selecting all instances in project
  src/components/SelectedTableNotification.tsx
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#559 fix(component) improved textarea height adjustment to fit content exactly
  .prettierrc
  src/components/AutoExpandingTextArea.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/util/formFields.tsx
Labels: Review: Code +1, Review: QA +1

#561 chore(tests) created tests for instance and profile panels WD-7370
  tests/helpers/instancePanel.ts
  tests/helpers/profileSummaryPanel.ts
  tests/instance-panel.spec.ts
  tests/profile-summary-panel.spec.ts
Labels: Review: Code +1, Review: QA needed

#562 chore(doc) include links for useful playwright functionalities
  HACKING.md
Labels: Review: Code +1
