Repository canonical/lxd-ui, pull requests merged in 2023-03, with the labels that each got.

#218 Use empty state component for empty snapshot list WD-2127
  static/js/pages/instances/InstanceSnapshots.tsx
  static/js/pages/instances/actions/snapshots/CreateSnapshotBtn.tsx
  static/sass/styles.scss
Labels: Review: Design needed, Review: Code needed

#219 Split device section into storage and network
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/forms/DevicesForm.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/instances/forms/NetworkForm.tsx
  src/pages/instances/forms/StorageForm.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/util/devices.tsx
  src/util/formDevices.tsx
Labels: Review: Design +1, Review: Code +1

#226 Prevent TypeError when image.description is undefined
  src/pages/instances/InstanceList.tsx
Labels: Bug 🐛, Review: Code needed, Review: QA needed

#227 Add .eslintignore to exclude external libraries (in src/lib) from eslint checks
  .eslintignore
Labels: Review: Code needed, Maintenance 🔨

#230 Explicitly declare config["image.description"] as optional
  src/types/instance.d.ts
Labels: Bug 🐛, Review: Code needed

#229 Ignore external libraries (in src/lib) in .prettierignore
  .prettierignore
Labels: Review: Code needed, Maintenance 🔨

#225 Instance list pagination WD-2591
  src/components/Pagination.tsx
  src/pages/instances/InstanceList.tsx
  src/sass/_pagination.scss
  src/sass/styles.scss
  src/util/paginationOptions.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#223 Adjust profile and image selector after design review WD-2561
  src/pages/images/ImageSelector.tsx
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/EditInstanceForm.tsx
  src/pages/instances/forms/InstanceDetailsForm.tsx
  src/pages/instances/forms/InstanceEditDetailsForm.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/instances/forms/SnapshotsForm.tsx
  src/pages/profiles/ProfileSelector.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/profiles/forms/ProfileEditDetailsForm.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/sass/_instance_forms.scss
  src/sass/_profile_select.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#232 Optimize initial bundle size, remove fonts, remove webpack WD-1229
  index-prd.html
  package.json
  public/assets/fonts/0c7b8dc0-Ubuntu-R-subset.woff2
  public/assets/fonts/22f97dd9-UbuntuMono-B-subset.woff
  public/assets/fonts/3baab91b-Ubuntu-Th-subset.woff2
  public/assets/fonts/4070835e-Ubuntu-L-subset.woff
  public/assets/fonts/46ed6870-Ubuntu-L-subset.woff2
  public/assets/fonts/56a10e22-Ubuntu-LI-subset.woff
  public/assets/fonts/6113b69a-Ubuntu-LI-subset.woff2
  public/assets/fonts/89be6515-Ubuntu-RI-subset.woff
  public/assets/fonts/a662364d-UbuntuMono-B-subset.woff2
  public/assets/fonts/a6c34b5d-UbuntuMono-R-subset.woff2
  public/assets/fonts/cb89e3ac-Ubuntu-Th-subset.woff
  public/assets/fonts/e6daa284-UbuntuMono-R-subset.woff
  public/assets/fonts/ef4d35ed-Ubuntu-R-subset.woff
  public/assets/fonts/fd4ec0c7-Ubuntu-RI-subset.woff2
  src/App.tsx
  src/sass/_font.scss
  src/sass/styles.scss
  tsconfig.node.json
  vite.config.ts
  webpack.config.js
  yarn.lock
Labels: Review: Code +1

#237 Merge profile detail forms for edit and create
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/EditProfileForm.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/profiles/forms/ProfileEditDetailsForm.tsx
Labels: Review: Code +1, Review: QA +1

#228 Overhaul Instance detail tab: Snapshots [WD-2552]
  src/components/ConfirmationButton.tsx
  src/components/NotificationRowLegacy.tsx
  src/context/notify.tsx
  src/pages/instances/InstanceDetail.tsx
  src/pages/instances/InstanceDetailPanel.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/actions/snapshots/CreateSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/CreateSnapshotForm.tsx
  src/pages/instances/actions/snapshots/DeleteSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/RestoreSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/SnapshotActions.tsx
  src/sass/_instance_detail_page.scss
  src/sass/_instance_detail_snapshots.scss
  src/sass/styles.scss
  src/util/helpers.tsx
  src/util/updateTBodyHeight.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA needed

#244 Set dark theme for YAML editor [WD-2549]
  src/pages/instances/forms/YamlForm.tsx
Labels: Review: Design +1

#243 Adjusted design of the terminal tab [WD-2553]
  src/pages/instances/InstanceDetail.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
  src/pages/instances/InstanceVga.tsx
  src/sass/_instance_detail_terminal.scss
  src/sass/styles.scss
  src/util/updateMaxHeight.tsx
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#250 Ensure to invalidate instances cache after an instance is created and started
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/InstanceGraphicConsole.tsx
Labels: Review: Code +1

#251 Copy updates WD-2767
  src/pages/instances/CreateInstanceForm.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/CreateProfileForm.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/ProfileSelector.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/sass/_instance_forms.scss
  src/sass/_instance_list.scss
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#256 Redesign the Reconnect terminal modal [WD-2772]
  src/pages/instances/TerminalPayloadForm.tsx
  src/sass/_instance_detail_terminal.scss
  src/util/updateMaxHeight.tsx
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#249 Set a min- and max-height for cloud-init config fields
  src/pages/instances/forms/CloudInitForm.tsx
  src/pages/profiles/CloudInitConfig.tsx
  src/sass/_instance_forms.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#260 Overhaul instance detail header [WD-2550]
  src/components/ConfirmationButton.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/pages/instances/InstanceDetail.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/PauseInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storages/actions/DeleteStorageBtn.tsx
  src/sass/_instance_detail_page.scss
  src/sass/_instance_list.scss
  src/sass/_pattern_icon.scss
  src/sass/styles.scss
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#265 Fix navigation toggle and logo are sticky WD-2987
  src/components/Navigation.tsx
  src/sass/_pattern_navigation.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1
