Repository canonical/lxd-ui, pull requests merged in 2024-09, with the labels that each got.

#871 feat: [WD-14390] Add bulk instance action tests.
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#872 Add export of instances WD-13701
  src/api/instances.tsx
  src/pages/instances/InstanceDetailActions.tsx
  src/pages/instances/actions/ExportInstanceBtn.tsx
  src/sass/_rename_header.scss
Labels: Review: Code needed, Review: QA needed

#877 simplify auto expanding text area component
  src/components/AutoExpandingTextArea.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/permissions/forms/GroupForm.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#873 feat: [WD-14392] Add tests for instance upload.
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#874 feat: [WD-12912] Add Application layout components
  src/Root.tsx
  src/components/BaseLayout.tsx
  src/components/CustomLayout.tsx
  src/components/Navigation.tsx
  src/components/SidePanel.tsx
  src/components/StatusBar.tsx
Labels: Review: Code needed, Review: QA needed

#876 Remove pinned version of requests library for pr workflows
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
Labels: Review: Code needed, Review: QA needed

#879 Show permissions in navigation also without oidc.audience being set.
  src/util/permissions.tsx
Labels: Review: Code needed

#878 Enable VM tests and reduce flaky tests
  .gitignore
  src/components/ConfigurationRow.tsx
  src/components/forms/MigrationForm.tsx
  src/components/forms/ResourceLimitsForm.tsx
  src/components/forms/SecurityPoliciesForm.tsx
  tests/instances.spec.ts
  tests/iso-volumes.spec.ts
Labels: Review: Code needed, Review: QA needed

#881 Add devices section to bundle all related entries in instance and profile form menu
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  tests/devices.spec.ts
  tests/helpers/instances.ts
  tests/readme-screenshots.spec.ts
Labels: Review: Code needed, Review: QA needed

#869 fix: remove bulk instance migration feature due to server loading concerns
  src/api/instances.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/instances/actions/BulkMigrateInstanceBtn.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/util/instanceMigrate.tsx
Labels: Review: Code needed, Review: QA needed

#886 feat: [WD-14771]- Get existing device names
  src/components/forms/DiskDeviceForm.tsx
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/GPUDeviceForm.tsx
  src/components/forms/OtherDeviceForm.tsx
  src/util/configInheritance.tsx
  src/util/devices.tsx
Labels: Review: Code +1, Review: QA +1

#887 Allow adding permisisons and identites when creatign a group. Simplify group editing
  src/components/Navigation.tsx
  src/components/PanelFormLink.tsx
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/actions/GroupActions.tsx
  src/pages/permissions/forms/GroupForm.tsx
  src/pages/permissions/panels/CreateGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/pages/permissions/panels/EditGroupPermissionsPanel.tsx
  src/pages/permissions/panels/EditIdentitiesForm.tsx
  src/pages/permissions/panels/GroupHeaderTitle.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/sass/_instance_list.scss
  src/sass/_panel-form-link.scss
  src/sass/_permission_groups.scss
  src/sass/_profile_list.scss
  src/sass/styles.scss
  src/util/permissions.spec.ts
  src/util/permissions.tsx
  src/util/usePanelParams.tsx
  tests/helpers/permission-groups.ts
  tests/helpers/permission-identities.ts
  tests/helpers/permission-idp-groups.ts
  tests/permission-groups.spec.ts
  tests/permission-identities.spec.ts
  tests/permission-idp-groups.spec.ts
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#781 chore: add oidc login tests [WD-9461]
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  CONTRIBUTING.md
  package.json
  playwright.config.ts
  tests/helpers/permission-identities.ts
  tests/images.spec.ts
  tests/login.spec.ts
  tests/scripts/create_oidc_identities
  tests/scripts/delete_oidc_identities
  tests/scripts/setup_test
  tests/scripts/teardown_test
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#892 Ensure storage volume is active when visiting a volume detail page
  src/components/NavLink.tsx
  src/components/Navigation.tsx
Labels: Review: Code +1, Review: QA +1

#894 fix: allow forked PRs to access repo secrets
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
Labels: Review: Code +1

#888 feat: [WD-14770] Device inheritance simplification
  src/util/configInheritance.tsx
Labels: Review: Code needed, Review: QA needed

#899 Auto name instance networks
  src/components/forms/NetworkDevicesForm.tsx
Labels: Review: Code +1, Review: QA +1

#900 fix(instance) adding a gpu without pci address will fall back to setting the cards drm id
  src/components/forms/GPUDeviceForm.tsx
Labels: Review: Code +1, Review: QA +1

#901 adjust other device copy to align with rest of the configuration
  src/components/forms/OtherDeviceForm.tsx
Labels: Review: Code +1, Review: QA +1

#902 fix(idp-group) deselect idp group after deletion, deselct idp group on cancel of edit panel
  src/pages/permissions/PermissionIdpGroups.tsx
  src/pages/permissions/actions/BulkDeleteIdpGroupsBtn.tsx
  src/pages/permissions/actions/DeleteIdpGroupBtn.tsx
  src/pages/permissions/panels/EditIdpGroupPanel.tsx
Labels: Review: Code +1, Review: QA +1

#907 Always allow OVN network creation
  src/pages/networks/forms/NetworkTypeSelector.tsx
Labels: Review: Code needed, Review: Code +1, Review: QA needed, Review: QA +1

#908 On permission select, show image names with image type (vm or container)
  src/util/permissions.tsx
Labels: Review: Code +1, Review: QA +1

#911 Show network parent in read and edit mode, when lxd is not clustered
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  tests/helpers/network.ts
Labels: Review: Code +1, Review: QA +1

#913 Allow root disk device to have a custom name
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/util/configInheritance.tsx
  src/util/instanceValidation.tsx
Labels: Review: Code +1, Review: QA +1

#890 feat: [WD-14882] Adjust Listen and Connect Inputs
  src/components/forms/ProxyDeviceForm.tsx
  src/util/instanceOptions.tsx
  src/util/proxyDevices.tsx
Labels: Review: Design needed, Review: Code needed, Review: QA needed

#903 Link identity and permission counts to the edit panel sections
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/util/permissions.tsx
  src/util/usePanelParams.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#904 feat: show cached images for instance creation [WD-14414]
  src/pages/images/ImageSelector.tsx
  src/types/image.d.ts
  src/util/images.tsx
  tests/helpers/instances.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#915 Show help text on instance location
  src/pages/instances/InstanceDetailPanelContent.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceLocationSelect.tsx
  src/pages/storage/StorageVolumeOverview.tsx
  src/sass/_cluster_list.scss
Labels: Review: Code +1, Review: QA +1

#893 Show change counts on save buttons for edit forms
  src/App.tsx
  src/components/ConfigurationRow.tsx
  src/components/forms/CloudInitForm.tsx
  src/components/forms/FormSubmitBtn.tsx
  src/components/forms/GPUDeviceInput.tsx
  src/components/forms/OtherDeviceForm.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/ProfileSelector.tsx
  src/pages/projects/EditProject.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StorageVolumeDetail.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
  src/pages/storage/forms/EditStorageVolume.tsx
  src/sass/_forms.scss
  src/util/formChangeCount.spec.ts
  src/util/formChangeCount.tsx
  tests/devices.spec.ts
  tests/helpers/instances.ts
  tests/helpers/profile.ts
  tests/helpers/storagePool.ts
  tests/helpers/storageVolume.ts
  tests/instances.spec.ts
  tests/profiles.spec.ts
  tests/projects.spec.ts
  tests/readme-screenshots.spec.ts
Labels: Review: Code +1, Review: QA +1

#921 Count removal of instance config override as one changed field on instance edit
  src/util/formChangeCount.spec.ts
  src/util/formChangeCount.tsx
Labels: Review: Code +1, Review: QA +1

#918 fix: remove workaround for extracting instance name from snapshot operation [WD-14541]
  src/types/operation.d.ts
  src/util/operations.spec.ts
  src/util/operations.tsx
Labels: Review: Code +1, Review: QA +1

#920 Preserve any disk device field on editing of instance or profile config
  src/components/ConfigurationRow.tsx
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/components/forms/InheritedDeviceRow.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
  src/types/device.d.ts
  src/util/formChangeCount.spec.ts
  src/util/formChangeCount.tsx
  src/util/formDevices.spec.ts
  src/util/formDevices.tsx
  src/util/formFields.tsx
Labels: Review: Code +1, Review: QA +1

#926 fix: update file conversion source disk size field name [WD-15110]
  src/util/uploadExternalFormatFile.tsx
Labels: Review: Code +1, Review: QA +1

#930 fix: update permission selector to use entity type metadata if api extension exists [WD-15109]
  src/context/useSupportedFeatures.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/types/config.d.ts
  src/util/permissions.spec.ts
  src/util/permissions.tsx
Labels: Review: Code +1, Review: QA +1

#916 feat: [WD-14769] Move custom storage volume to another storage pool.
  src/api/storage-pools.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/MigrateVolumeModal.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/actions/DeleteStorageVolumeBtn.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  tests/helpers/storageVolume.ts
  tests/storage.spec.ts
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#923 feat: [WD-14774] Proxy Device Test
  src/util/proxyDevices.tsx
  tests/devices.spec.ts
Labels: Review: Code +1, Review: QA +1

#933 Fix various UI bugs
  src/components/forms/DiskDeviceFormRoot.tsx
  src/components/forms/ProxyDeviceForm.tsx
  src/context/eventQueue.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/images/actions/forms/UploadImageForm.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
Labels: Review: Code +1, Review: QA +1

#925 feat: [WD-14775] Other Device(s) Test
  tests/devices.spec.ts
  tests/helpers/devices.ts
Labels: Review: Code +1, Review: QA +1

#929 test: add e2e test for external instance file [WD-14777]
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  src/pages/cluster/ClusterMemberSelector.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/util/uploadExternalFormatFile.tsx
  tests/instances.spec.ts
Labels: Review: Code needed, Review: QA needed
