Repository canonical/lxd-ui, pull requests merged in 2024-10, with the labels that each got.

#935 feat(gpu) add gpu device test WD-14776
  tests/devices.spec.ts
  tests/helpers/devices.ts
Labels: Review: Code needed

#927 chore: retry lazy load components when server is down [WD-13909]
  src/App.tsx
  src/components/ErrorPage.tsx
  src/components/ProtectedRoute.tsx
  src/util/helpers.tsx
  src/util/lazyWithRetry.tsx
Labels: Review: Code +1, Review: QA +1

#917 feat: move instance root volume to another storage pool [WD-14768]
  src/api/instances.tsx
  src/components/BackLink.tsx
  src/components/FormLink.tsx
  src/components/PanelFormLink.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/pages/cluster/ClusterMemberSelectTable.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/InstanceClusterMemberMigration.tsx
  src/pages/instances/InstanceStoragePoolMigration.tsx
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/permissions/forms/GroupForm.tsx
  src/pages/permissions/panels/GroupHeaderTitle.tsx
  src/pages/storage/MigrateVolumeModal.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/sass/_form-link.scss
  src/sass/_migrate_instance.scss
  src/sass/styles.scss
  src/util/instanceEdit.tsx
  src/util/instanceMigration.tsx
  tests/helpers/cluster.ts
  tests/helpers/instances.ts
  tests/instances.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#924 feat: duplicate custom storage volume [WD-15107]
  src/api/storage-pools.tsx
  src/context/useSupportedFeatures.tsx
  src/pages/cluster/ClusterMemberSelector.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/StorageVolumeOverview.tsx
  src/pages/storage/actions/DuplicateVolumeBtn.tsx
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/types/storage.d.ts
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#912 feat: custom single option select component [WD-10960]
  src/components/select/CustomSelect.tsx
  src/components/select/CustomSelectDropdown.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/sass/_custom_select.scss
  src/sass/_permission_groups.scss
  src/sass/styles.scss
  src/util/customSelect.spec.ts
  src/util/customSelect.tsx
  src/util/permissions.spec.ts
  src/util/permissions.tsx
  tests/helpers/permission-groups.ts
  tests/permission-groups.spec.ts
Labels: Review: Code needed, Review: QA needed

#937 tests: add e2e for duplicating custom storage volume
  tests/helpers/storageVolume.ts
  tests/storage.spec.ts
Labels: Review: Code needed

#938 fix: [WD-15307] Truncate instance name in instance list (when creatin…
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#941 fix: migrate custom volume in non-default project
  src/api/storage-pools.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
Labels: Review: Code needed, Review: QA needed

#944 feat: [WD-15296] Disable other devices for LXD 5.0
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  tests/instances.spec.ts
  tests/profiles.spec.ts
Labels: Review: Code needed, Review: QA needed

#949 fix(image) image creation, and export in custom projects
  src/api/images.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/actions/DownloadImageBtn.tsx
  src/pages/images/actions/forms/UploadImageForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
  tests/helpers/snapshots.ts
  tests/images.spec.ts
Labels: Review: Code +1, Review: QA +1

#951 fix: un-select items when closing permission side panels
  src/components/SidePanel.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditIdentityGroupsPanel.tsx
  src/pages/permissions/panels/EditIdpGroupPanel.tsx
Labels: Review: Code +1, Review: QA +1

#952 feat: Add resource link and label components [WD-15623]
  src/components/ResourceIcon.tsx
  src/components/ResourceLabel.tsx
  src/components/ResourceLink.tsx
  src/sass/_resources.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#940 feat: improve permission selector [WD-15106]
  src/api/auth-permissions.tsx
  src/components/select/CustomSelect.tsx
  src/components/select/CustomSelectDropdown.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EntitlementOptionLabel.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/pages/permissions/panels/ResourceOptionHeader.tsx
  src/pages/permissions/panels/ResourceOptionLabel.tsx
  src/sass/_custom_select.scss
  src/sass/_permission_groups.scss
  src/types/image.d.ts
  src/util/permissions.spec.ts
  src/util/permissions.tsx
  src/util/resourceDetails.spec.ts
  src/util/resourceDetails.tsx
  tests/helpers/permission-groups.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#953 Prevent local volume attach to instances on another cluster member
  src/api/storage-pools.tsx
  src/components/forms/DiskDeviceFormCustom.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/CustomVolumeModal.tsx
  src/pages/storage/CustomVolumeSelectBtn.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/instanceLocation.tsx
  tests/helpers/devices.ts
Labels: Review: Code +1, Review: QA +1

#954 Remove project parameter from storage pool api
  src/api/storage-pools.tsx
  src/components/forms/DiskDeviceForm.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/context/loadIsoVolumes.tsx
  src/pages/instances/InstanceStoragePoolMigration.tsx
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/pages/instances/forms/UploadInstanceBackupFileForm.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/MigrateVolumeModal.tsx
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StoragePoolHeader.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/configInheritance.tsx
Labels: Review: Code +1, Review: QA +1

#955 feat: semiotics update overview pages [WD-15624]
  src/components/UsedByItem.tsx
  src/pages/images/ImageName.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/InstanceOverviewDevices.tsx
  src/pages/instances/InstanceOverviewNetworks.tsx
  src/pages/instances/InstanceOverviewProfiles.tsx
  src/pages/networks/NetworkDetailOverview.tsx
  src/pages/profiles/ProfileDetailOverview.tsx
  src/pages/profiles/ProfileDetailPanelContent.tsx
  src/pages/profiles/ProfileNetworkList.tsx
  src/pages/profiles/ProfileStorageList.tsx
  src/pages/storage/StorageUsedBy.tsx
  src/pages/storage/StorageVolumeOverview.tsx
  src/sass/_resources.scss
Labels: Review: Code +1, Review: QA +1

#956 feat: general semiotics improvements [WD-15264]
  src/components/ToastNotificationList.tsx
  src/pages/images/actions/UploadCustomIsoBtn.tsx
  src/pages/images/actions/UploadImageBtn.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/StoragePoolHeader.tsx
  src/pages/storage/actions/CreateStoragePoolBtn.tsx
  src/pages/storage/actions/CreateVolumeBtn.tsx
  src/pages/storage/actions/CustomIsoBtn.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/sass/_toast.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#960 fix(semiotics) enhance usage of chips and add context to notifications
  src/components/ResourceIcon.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotActions.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
  src/pages/settings/SettingForm.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotActions.tsx
  src/pages/storage/forms/CreateVolumeSnapshotForm.tsx
  tests/helpers/snapshots.ts
  tests/snapshots.spec.ts
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#961 chore(ci) cancel pr workflow on subsequent pushes to the same branch
  .github/workflows/pr.yaml
Labels: Review: Code +1

#962 fix(instance) remove read and write limits for custom storage volumes
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/DiskDeviceFormInherited.tsx
  src/util/formDevices.tsx
Labels: Review: Code +1, Review: QA +1

#963 chore(security) add security.md
  SECURITY.md
Labels: Review: QA needed

#965 feat: [WD-15078] Add skip to content button
  src/Root.tsx
  src/components/BaseLayout.tsx
  src/components/CustomLayout.tsx
Labels: Review: Code +1, Review: QA +1

#964 fix(cache) force cache refetch when lifecycle events come in
  src/pages/instances/Events.tsx
Labels: Review: Code +1, Review: QA +1

#967 feat: [WD-15994] Show Instance device details on Overview page.
  src/pages/instances/InstanceOverviewDeviceDetail.tsx
  src/pages/instances/InstanceOverviewDevices.tsx
Labels: Review: Code +1, Review: QA +1

#969 fix(instance) layout adjustments for the instance overview tab
  src/pages/instances/InstanceOverviewDeviceDetail.tsx
  src/pages/instances/InstanceOverviewDevices.tsx
  src/sass/_instance_detail_overview.scss
  src/sass/_resources.scss
Labels: Review: Code +1, Review: QA +1

#970 fix: remove publish to gh-pages from workflows
  .github/workflows/delete_test_reports.yml
  .github/workflows/pr.yaml
  .github/workflows/publish_test_reports.yml
Labels: Review: Code needed

#973 fix(instance) show help text for instance root disk device on edit
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
Labels: Review: Code +1, Review: QA +1
