Repository canonical/lxd-ui, pull requests merged in 2024-01, with the labels that each got.

#577 feat(storage) add warning for project snapshot restriction [WD-7885]
  src/components/SnapshotDiabledWarningLink.tsx
  src/components/forms/InstanceSnapshotsForm.tsx
  src/pages/instances/actions/snapshots/InstanceAddSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeAddSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotModal.tsx
  src/pages/storage/forms/StorageVolumeFormSnapshots.tsx
  src/pages/storage/forms/StorageVolumeSnapshotsForm.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#595 Add error boundaries WD-8089
  src/Root.tsx
  src/components/ErrorBoundary.tsx
  src/components/ErrorPage.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#572 Add network forwards
  .github/workflows/pr.yaml
  src/App.tsx
  src/api/network-forwards.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/instances/InstanceOverviewNetworks.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkForwardCount.tsx
  src/pages/networks/NetworkForwardPort.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/NetworkMap.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/networks/actions/DeleteNetworkForwardBtn.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
  src/pages/networks/forms/NetworkForwardFormPorts.tsx
  src/sass/_network_forwards_form.scss
  src/sass/styles.scss
  src/types/network.d.ts
  src/util/networks.spec.tsx
  src/util/networks.tsx
  src/util/queryKeys.tsx
  tests/helpers/network.ts
  tests/networks.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#597 feature(storage): support ceph storage pool [WD-7968]
  src/api/storage-pools.tsx
  src/components/ConfigurationRow.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StoragePoolSize.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormCeph.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeFormMenu.tsx
  src/types/storage.d.ts
  src/util/configInheritance.tsx
  src/util/storageOptions.tsx
  src/util/storagePool.tsx
  src/util/storagePoolEdit.tsx
Labels: Review: Code +1, Review: QA +1

#602 fix: remove linuxcontainers images
  src/pages/images/ImageSelector.tsx
  tests/helpers/instances.ts
Labels: Review: Code needed, Review: QA needed

#600 feat: use supported storage driver options from server settings [WD-8144]
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/types/server.d.ts
  src/util/storageOptions.tsx
Labels: Review: Code +1, Review: QA +1

#601 Fix safari regressions [WD-7486]
  src/sass/_selectable_main_table.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#606 Avoid prompt on navigation away from terminal after session close
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
Labels: Review: Code +1, Review: QA +1

#608 Update dependencies to vite 5
  .eslintrc.cjs
  package.json
  src/App.tsx
  src/pages/profiles/ProfileInstances.tsx
  src/pages/storage/Storage.tsx
  src/util/projects.tsx
  tsconfig.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#609 use wasm-node to unlock builds for the linux/s390x architecture
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#611 Use documentation links from objects.inv.txt file shipped with lxd WD-8064
  src/api/server.tsx
  src/pages/settings/ConfigFieldDescription.tsx
  src/util/config.spec.tsx
  src/util/config.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#616 Fix notify.queue calls to only submit notification once
  package.json
  src/Root.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/cluster/actions/DeleteClusterGroupBtn.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/NetworkDetailHeader.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/ProfileDetailHeader.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/StoragePoolHeader.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotModal.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotActions.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotBulkDelete.tsx
  src/pages/storage/forms/CreateVolumeSnapshotForm.tsx
  src/pages/storage/forms/EditVolumeSnapshotForm.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#598 feat: use TablePagination component from react-components for paginating tables [WD-8209]
  src/components/ConfigurationTable.tsx
  src/components/Pagination.tsx
  src/components/ScrollableTable.tsx
  src/components/SelectableMainTable.tsx
  src/components/forms/ScrollableConfigurationTable.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/StorageVolumes.tsx
  src/sass/_pagination.scss
  src/sass/styles.scss
  src/util/pagination.tsx
  src/util/useSortTableData.tsx
Labels: Review: Code +1, Review: QA +1

#613 Remove unused dependencies
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#621 Use vitest instead of react-scripts for tests
  package.json
  src/util/config.spec.ts
  src/util/formDevices.spec.ts
  src/util/networks.spec.ts
  src/util/operations.spec.ts
  src/util/searchAndFilter.spec.ts
  src/util/storageVolume.spec.ts
  src/util/usedBy.spec.ts
  tests/devices.spec.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: Review: Code +1

#625 feat: upgrade to xterm v5 and remove xterm-for-react dependency [WD-8311]
  package.json
  src/components/Xterm.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
  src/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#626 chore: add test for using instance terminal [WD-8310]
  tests/helpers/instances.ts
  tests/instances.spec.ts
Labels: Review: Code needed

#628 Replace admonition markup in help texts
  src/util/config.spec.ts
  src/util/config.tsx
Labels: Review: Code +1, Review: QA +1
