Repository canonical/lxd-ui, pull requests merged in 2024-03, with the labels that each got.

#686 Ensure noopener is set on all outgoing links
  src/components/HelpLink.tsx
  src/components/Navigation.tsx
  src/components/NoMatch.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/UploadCustomImageHint.tsx
  src/pages/storage/forms/StorageVolumeFormBlock.tsx
  src/pages/storage/forms/StorageVolumeFormSnapshots.tsx
  src/util/config.spec.ts
  src/util/config.tsx
Labels: Review: Code +1, Review: QA +1

#684 Update tics after code coverage is produced
  .github/workflows/coverage.yaml
Labels: Review: Code needed

#673 Make rows in iso and custom-volume modals clickable
  src/pages/images/CustomIsoSelector.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/sass/_custom_isos.scss
  src/sass/_storage_volume_form.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#687 feat: added zfs storage pool configs [WD-8615]
  src/api/storage-pools.tsx
  src/components/ConfigurationRow.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StoragePoolFormZFS.tsx
  src/util/storagePool.tsx
  src/util/storagePoolEdit.tsx
Labels: Review: Code +1, Review: QA +1

#689 Show error message, when API requests fail
  src/api/images.tsx
  src/api/instance-snapshots.tsx
  src/api/instances.tsx
  src/api/volume-snapshots.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/AttachIsoBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/FreezeInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/instances/actions/snapshots/InstanceConfigureSnapshotModal.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotActions.tsx
  src/pages/instances/forms/EditInstanceSnapshotForm.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotActions.tsx
  src/pages/storage/forms/EditVolumeSnapshotForm.tsx
  src/util/instanceStart.tsx
Labels: Review: Code +1, Review: QA +1

#679 Add powerflex driver support
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StoragePoolFormPowerflex.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormBlock.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/types/config.d.ts
  src/types/storage.d.ts
  src/util/storageOptions.tsx
  src/util/storagePool.tsx
  src/util/storagePoolEdit.tsx
  src/util/storageVolume.tsx
  src/util/storageVolumeEdit.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#676 Add storage pool configuration as yaml
  src/components/forms/YamlConfirmation.tsx
  src/components/forms/YamlForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/sass/_forms.scss
  src/util/networkForm.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#692 feat: multi-select rows with shift key [WD-8506]
  src/components/SelectableMainTable.tsx
Labels: Review: Code +1, Review: QA +1

#696 fix: create instance from custom iso
  src/pages/instances/CreateInstance.tsx
Labels: Review: Code +1, Review: QA +1

#695 Use config api for network form help texts and defaults
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/pages/networks/forms/NetworkFormDns.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormIpv6.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/types/config.d.ts
  src/util/configInheritance.tsx
  src/util/networkForm.tsx
  src/util/networks.tsx
  tests/networks.spec.ts
Labels: Review: Code +1, Review: QA +1

#697 Add warning page test
  tests/warnings.spec.ts
Labels: Review: Code +1

#698 feat: refactor side panels and enabled overlay panels
  src/components/Aside.tsx
  src/components/DetailPanel.tsx
  src/components/SidePanel.tsx
  src/pages/instances/InstanceDetailPanel.tsx
  src/pages/instances/InstanceDetailPanelContent.tsx
  src/pages/profiles/ProfileDetailPanel.tsx
  src/pages/profiles/ProfileDetailPanelContent.tsx
  src/sass/_side_panel.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#701 Verious code style fixes
  src/context/instanceLoading.tsx
  src/pages/profiles/ProfileDetailPanelContent.tsx
Labels: Review: Code needed

#703 Ensure deps are installed before running the tics report
  .github/workflows/coverage.yaml
Labels: Review: Code needed

#702 Forward scroll event from vm to parent container
  src/lib/spice/src/inputs.js
  src/lib/spice/src/resize.js
  src/pages/instances/InstanceGraphicConsole.tsx
Labels: Review: Code +1, Review: QA +1

#708 feat: limit functionalities for storage pool with driver that's not fully supported in the UI [WD-9345]
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/storageOptions.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#710 Include yaml editor code in build
  package.json
  src/components/forms/YamlForm.tsx
  vite.config.ts
Labels: Review: Code +1

#714 Fix workflow: stop dotrun before uploading coverage report
  .github/workflows/coverage.yaml
Labels: Review: QA +1

#711 Ensure login button is not broken into two rows
  src/pages/login/Login.tsx
  src/sass/_login.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#712 Add tests for custom fields on all entities
  src/pages/profiles/EditProfile.tsx
  src/pages/projects/EditProject.tsx
  src/util/instanceEdit.spec.ts
  src/util/networkForm.spec.ts
  src/util/profileEdit.spec.ts
  src/util/profileEdit.tsx
  src/util/projectEdit.spec.ts
  src/util/projectEdit.tsx
  src/util/storagePoolForm.spec.ts
  src/util/storageVolumeForm.spec.ts
  vitest.config.ts
Labels: Review: Code +1
