Repository canonical/lxd-ui, pull requests merged in 2024-02, with the labels that each got.

#627 fix: add dynamic routes for editting storage pool and project configs [WD-8467]
  src/App.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/forms/ProjectForm.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StorageUsedBy.tsx
  src/pages/storage/StorageVolumeDetail.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/StorageVolumeNameLink.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StorageVolumeEdit.tsx
  tests/projects.spec.ts
Labels: Review: Code +1, Review: QA +1

#629 Update network forward and storage pool copy
  src/pages/networks/forms/NetworkForwardForm.tsx
  src/pages/storage/StorageUsedBy.tsx
Labels: Review: Code +1, Review: QA +1

#620 Allow bulk select/delete images in a project and unify pagination placement
  src/App.tsx
  src/api/images.tsx
  src/components/PageHeader.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/Images.tsx
  src/pages/images/actions/BulkDeleteImageBtn.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSearchFilter.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/StorageVolumeDetail.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/sass/_images.scss
  src/sass/_instance_list.scss
  src/sass/_page_header.scss
  src/sass/_profile_list.scss
  src/sass/_snapshots.scss
  src/sass/_storage.scss
  src/sass/styles.scss
  src/util/instanceBulkActions.tsx
  src/util/storageVolumeTable.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#633 fix: fix styling for actions list after v0.49.0 update for react-components
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#636 Fix storage pool navigation on create form
  src/pages/storage/CreateStoragePool.tsx
Labels: Review: Code +1, Review: QA +1

#637 fix: remove unsed ref from ScrollableTable
  src/components/ScrollableTable.tsx
Labels: Review: Code +1, Review: QA +1

#639 Make code snippet in `ErrorPage` scrollable, keeping rest of the page fixed
  src/components/ErrorPage.tsx
  src/sass/_error_page.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#641 chore: speed up e2e tests [WD-8560]
  .github/workflows/pr.yaml
  playwright.config.ts
  tests/helpers/instances.ts
  tests/instance-panel.spec.ts
  tests/instances.spec.ts
  tests/networks.spec.ts
  tests/notification.spec.ts
  tests/profiles.spec.ts
  tests/storage.spec.ts
Labels: Review: Code +1

#645 Simplify loading state and avoid races on start/stopping of instances
  src/context/instanceLoading.tsx
  src/pages/networks/NetworkForwards.tsx
Labels: Review: Code +1, Review: QA +1

#644 Add scrolling for network forwards
  src/pages/networks/NetworkForwards.tsx
Labels: Review: Code +1, Review: QA +1

#646 fix: redirect back to specific form section on creation error [WD-8681]
  src/pages/instances/CreateInstance.tsx
Labels: Review: Code +1, Review: QA +1

#652 Use correct type in server.d.ts
  src/types/server.d.ts
Labels: Review: Code +1

#651 Remove dead code
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkList.tsx
  src/util/limits.tsx
Labels: Review: Code +1

#650 Add return type to all util functions
  src/util/clusterGroups.tsx
  src/util/config.tsx
  src/util/cookies.tsx
  src/util/formDevices.tsx
  src/util/helpers.tsx
  src/util/images.tsx
  src/util/instanceBulkActions.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceEdit.tsx
  src/util/instanceFilter.tsx
  src/util/instanceSnapshots.tsx
  src/util/instanceValidation.tsx
  src/util/instances.tsx
  src/util/limits.tsx
  src/util/networks.tsx
  src/util/projects.tsx
  src/util/queryKeys.tsx
  src/util/searchAndFilter.tsx
  src/util/settings.tsx
  src/util/slugify.tsx
  src/util/snapshots.tsx
  src/util/storageOptions.tsx
  src/util/storageVolume.tsx
  src/util/title.tsx
  src/util/updateMaxHeight.tsx
  src/util/usePreferReducedMotion.tsx
  src/util/yaml.tsx
Labels: Review: Code +1

#647 feat: provide UI backward compatibility for older lxd versions [WD-8671]
  src/api/server.tsx
  src/context/useDocs.tsx
  src/context/useSupportedFeatures.tsx
  src/pages/instances/InstanceConsole.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/settings/ConfigFieldDescription.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/Storage.tsx
  src/types/server.d.ts
  src/util/configInheritance.tsx
Labels: Review: Code +1, Review: QA +1

#654 Use pluralize helper consistently
  src/components/SelectedTableNotification.tsx
  src/pages/instances/actions/InstanceBulkAction.tsx
  src/pages/instances/actions/InstanceBulkActions.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotBulkDelete.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotBulkDelete.tsx
  src/util/instanceBulkActions.tsx
Labels: Review: Code +1

#653 chore(test): added tests for multiple lxd server versions [WD-8616]
  .github/workflows/pr.yaml
  HACKING.md
  package.json
  playwright.config.ts
  tests/cluster.spec.ts
  tests/devices.spec.ts
  tests/fixtures/lxd-test.ts
  tests/helpers/configuration.ts
  tests/instance-panel.spec.ts
  tests/instances.spec.ts
  tests/iso-volumes.spec.ts
  tests/networks.spec.ts
  tests/notification.spec.ts
  tests/profile-summary-panel.spec.ts
  tests/profiles.spec.ts
  tests/projects.spec.ts
  tests/server.spec.ts
  tests/snapshots.spec.ts
  tests/storage.spec.ts
  tsconfig.json
Labels: Review: Code +1, Review: QA +1

#657 Comply coding conventions
  src/components/Xterm.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/context/toastNotificationProvider.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
Labels: Review: Code +1

#661 Comply to coding standards
  src/components/Animate.tsx
  src/components/StatusBar.tsx
  src/components/ToastNotificationList.tsx
  src/context/menuCollapsed.tsx
  src/pages/images/CustomIsoModal.tsx
  src/pages/images/ImageSelector.tsx
Labels: Review: Code +1

#659 Update pr template help text
  .github/pull_request_template.md
Labels: Review: Code +1

#660 fix: merge playwright reports with assets
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1

#658 Update cookie name after upstream change #569
  src/App.tsx
  src/components/Navigation.tsx
  src/components/StatusBar.tsx
  src/context/auth.tsx
  src/context/operationsProvider.tsx
  src/types/server.d.ts
  src/util/cookies.tsx
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#662 fix: avoid empty label for a11y compliance
  src/pages/networks/forms/IpAddressSelector.tsx
  src/sass/_forms.scss
Labels: Review: Code +1, Review: QA +1

#634 Add test coverage
  .github/workflows/coverage.yaml
  .gitignore
  package.json
  playwright.config.ts
  src/util/helpers.tsx
  tests/fixtures/coverage.ts
  tests/fixtures/lxd-test.ts
  tests/helpers/network.ts
  tests/instance-panel.spec.ts
  tests/instances.spec.ts
  tests/iso-volumes.spec.ts
  tests/networks.spec.ts
  tests/notification.spec.ts
  tests/profiles.spec.ts
  tests/projects.spec.ts
  tests/server.spec.ts
  tests/storage.spec.ts
  vitest.config.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#667 fix: table pagination margin bottom
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#668 Add coverage report as zip file
  .github/workflows/coverage.yaml
Labels: Review: Code +1

#666 chore(doc): added new instructions for e2e test with different lxd versions [WD-9034]
  ARCHITECTURE.MD
  HACKING.md
Labels: Review: Code needed

#663 Use action button for a consistent loading button behaviour with vanilla guidelines
  src/components/RenameHeader.tsx
  src/components/SubmitButton.tsx
  src/components/forms/SnapshotForm.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/InstanceConsole.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/MigrateInstanceForm.tsx
  src/pages/instances/TerminalPayloadForm.tsx
  src/pages/instances/actions/snapshots/InstanceConfigureSnapshotModal.tsx
  src/pages/login/PasswordModal.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotModal.tsx
  src/pages/storage/forms/StorageVolumeCreate.tsx
  src/pages/storage/forms/StorageVolumeEdit.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#672 Keep covarge on navigation
  tests/fixtures/coverage.ts
  tests/fixtures/lxd-test.ts
  tests/instance-panel.spec.ts
  tests/instances.spec.ts
  tests/networks.spec.ts
  tests/notification.spec.ts
  tests/profiles.spec.ts
  tests/storage.spec.ts
Labels: Review: Code +1

#674 Fix event handling and e2e tests
  src/pages/instances/Events.tsx
Labels: Review: Code +1

#680 Avoid test coverage report with failing tests
  package.json
Labels: Review: Code +1

#682 Add note about license and copyright to HACKING.md
  HACKING.md
Labels: Review: QA needed

#683 Fix used by links to snapshots of custom storage volumes
  src/pages/storage/StorageUsedBy.tsx
  src/util/usedBy.spec.ts
  src/util/usedBy.tsx
Labels: Review: Code +1, Review: QA +1

#678 Add link to storage pool from storage volume
  src/pages/storage/StorageVolumeOverview.tsx
  tests/storage.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1
