Repository canonical/lxd-ui, pull requests merged in 2024-06, with the labels that each got.

#784 More detailed error message when user has no access
  src/App.tsx
  src/components/NoProject.tsx
  src/context/auth.tsx
  src/pages/projects/ProjectLoader.tsx
Labels: Review: Code +1, Review: QA +1

#779 [WD-10833] - Indicate logged-in-user-email
  src/components/Navigation.tsx
  src/context/useLoggedInUser.tsx
  src/sass/_pattern_navigation.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#785 [WD-11261] Implementation of LXD PWA with a dynamic start_url
  index.html
  public/assets/img/LXD-screenshot.png
  public/assets/img/LXD-screenshot2.png
  public/assets/img/LXD-screenshot3.png
  public/assets/img/canonical-lxd-512.png
  public/assets/js/manifest.js
Labels: Review: Code +1, Review: QA +1

#790 Use doc link titles as link text in case they are available
  src/util/config.spec.ts
  src/util/config.tsx
Labels: Review: Code +1, Review: QA +1

#791 [WD-11661] feat: Added 2 storage e2e test to increase coverage.
  tests/helpers/storagePool.ts
  tests/helpers/storageVolume.ts
  tests/storage.spec.ts
Labels: Review: Code needed

#789 [WD-11114] Feat: Improving tests by using text assertion
  tests/devices.spec.ts
  tests/helpers/permissions.ts
  tests/instances.spec.ts
  tests/iso-volumes.spec.ts
  tests/permission-groups.spec.ts
  tests/permission-identities.spec.ts
  tests/profiles.spec.ts
  tests/projects.spec.ts
  tests/storage.spec.ts
  tests/warnings.spec.ts
Labels: Review: Code needed, Review: QA needed

#792 Allow creation and editing of physical managed networks
  src/api/networks.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/NetworkDetailOverview.tsx
  src/pages/networks/forms/IpAddressSelector.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormDns.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormIpv6.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/networks/forms/NetworkFormOvn.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/types/network.d.ts
  src/util/networkForm.tsx
  src/util/networks.tsx
  tests/helpers/network.ts
  tests/networks.spec.ts
Labels: Review: Code +1, Review: QA +1, Docs needed

#793 [WD-11660] LXD-UI e2e test for operations
  tests/helpers/operations.ts
  tests/operations.spec.ts
Labels: Review: Code needed

#795 [WD-11889] LXD add e2e testing for doc links
  tests/doc-links.spec.ts
  tests/helpers/doc-links.ts
  tests/helpers/server.ts
Labels: Review: Code needed

#798 Add roadmap and extend readme
  .github/pull_request_template.md
  CONTRIBUTING.md
  HACKING.md
  README.md
  ROADMAP.md
Labels: Review: QA +1

#803 chore: Adjusted detail page titles for better ux consistency [WD-11696]
  src/components/RenameHeader.tsx
  src/pages/instances/InstanceDetail.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/sass/_rename_header.scss
  src/sass/styles.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#797 [WD-11691] chore: minor UI change for vertical navigation resizing.
  src/components/Navigation.tsx
  src/sass/_pattern_navigation.scss
Labels: Review: Design +1, Review: Code +1, Review: QA +1
