Repository canonical/lxd-ui, pull requests merged in 2024-11, with the labels that each got.

#974 feat(instance) add cluster member column and filter to instance list
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSearchFilter.tsx
  src/util/instanceFilter.tsx
  src/util/instanceTable.tsx
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#972 feat: [WD-15753] Delete OIDC User
  src/api/auth-identities.tsx
  src/context/useSupportedFeatures.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/actions/BulkDeleteIdentitiesBtn.tsx
  src/pages/permissions/actions/DeleteIdentityBtn.tsx
  tests/permission-identities.spec.ts
Labels: Review: Code +1, Review: QA +1

#975 feat: [WD-15550] Adding an sbom workflow
  .github/workflows/sbom_generation.yaml
Labels: Review: QA needed

#980 chore(docs) add roadmap for 25.04
  ROADMAP.md
Labels: Review: Code +1

#981 clarify ipv4 address label on network creation
  src/pages/networks/forms/IpAddressSelector.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/sass/_forms.scss
Labels: Review: Code needed, Review: QA needed

#982 feat: [WD-16398] Set default storage pool for new project...
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/util/helpers.tsx
  src/util/projectEdit.tsx
Labels: Review: Design needed, Review: Code needed, Review: QA needed

#968 feat: [WD-16007] Replace storage list with device list on profile det…
  src/components/DeviceDetails.tsx
  src/components/DeviceListTable.tsx
  src/components/NetworkListTable.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/InstanceOverviewDevices.tsx
  src/pages/profiles/ProfileDetailOverview.tsx
  src/sass/_device_detail_list.scss
  src/sass/_instance_detail_overview.scss
  src/sass/_network_detail_list.scss
  src/sass/_profile_detail_overview.scss
  src/sass/styles.scss
  src/util/helpers.tsx
Labels: Review: Code needed, Review: QA needed

#984 fix(profile) ensure space in hint about modifications
  src/pages/profiles/ProfileDetailOverview.tsx
Labels: Review: Code +1, Review: QA +1

#979 Allow auto assignment of listen address when creating a network forward
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormIpv6.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
Labels: Review: Code +1, Review: QA +1

#983 fix(edit) instance and profile configuration: clear cpu or memory limit
  src/util/formChangeCount.tsx
  tests/helpers/configuration.ts
  tests/profiles.spec.ts
Labels: Review: Code needed, Review: QA needed

#990 feat(logo) use microcloud logo, in case user.microcloud server setting is present
  public/assets/img/microCloud-logo.svg
  src/components/Logo.tsx
Labels: Review: Code +1, Review: QA +1

#988 simplify keys setup
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  entrypoint
  haproxy-dev.cfg
Labels: Review: Code +1

#986 Fix warnings from TICS scan
  src/components/forms/DiskDeviceFormRoot.tsx
  src/pages/cluster/ClusterMemberSelectTable.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
Labels: Review: Code +1

#995 fix(logo) condition for microcloud is presence of user.microcloud
  src/components/Logo.tsx
Labels: Review: Code needed

#997 feat(instance) add boot config keys for instances and profiles
  src/components/forms/BootForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceEdit.tsx
  src/util/profileEdit.tsx
Labels: Review: Code +1, Review: QA +1

#1000 fix: avoid duplicate tooltip for disabled rename header
  src/components/RenameHeader.tsx
Labels: Review: Code +1, Review: QA +1

#998 Add support for cephfs backed storage pools and volumes on it
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormCephFS.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/util/storageOptions.tsx
  src/util/storagePool.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Code needed, Review: QA needed

#1002 fix custom select
  src/components/select/CustomSelect.tsx
  src/components/select/CustomSelectDropdown.tsx
  src/sass/_custom_select.scss
  src/util/zIndex.tsx
Labels: Review: Code +1, Review: QA +1

#1001 Cleanup
  src/pages/instances/InstanceOverviewDevices.tsx
  src/util/helpers.tsx
  src/util/proxyDevices.tsx
Labels: Review: Code needed, Review: QA needed

#1006 fix(project) sum of memory limits is a size with unit
  src/pages/projects/forms/ProjectResourceLimitsForm.tsx
  src/util/projectEdit.tsx
  tests/projects.spec.ts
Labels: Review: Code +1, Review: QA +1

#1007 filter out networks of type unknown or loopback
  src/api/networks.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
Labels: Review: Code +1, Review: QA +1

#1009 avoid invalid label on custom select options
  src/components/select/CustomSelectDropdown.tsx
Labels: Review: Code needed, Review: QA needed

#1011 volume snapshots can have an empty expiry
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#1013 Improve design of project form
  src/pages/projects/CreateProject.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
Labels: Review: Code needed, Review: QA needed

#1014 Link image and cluster member on instance overview page
  src/pages/instances/InstanceOverview.tsx
Labels: Review: Design needed, Review: Code needed

#1015 Add airgap support
  public/assets/font/90b59210-Ubuntu-Italic-latin-v0.896a.woff2
  public/assets/font/d5fc1819-UbuntuMono-latin-v0.869.woff2
  public/assets/font/f1ea362b-Ubuntu-latin-v0.896a.woff2
  public/assets/icon/contextual-menu.svg
  src/pages/images/ImageSelector.tsx
  src/sass/_font.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1017 Use all projects parameter to resolve image fingerprints in permission config
  src/api/images.tsx
  src/util/permissions.tsx
Labels: Review: Code +1, Review: QA +1
