Repository canonical/lxd-ui, pull requests merged in 2024-07, with the labels that each got.

#812 chore(readme) suggest the default channel when installing lxd
  README.md
Labels: Review: Code needed

#817 Remove ticls report upload to prevent a security issue
  .github/workflows/coverage.yaml
Labels: Review: Code +1

#818 fix: prevent settings form input from submitting multiple requests
  src/pages/settings/SettingFormInput.tsx
Labels: Review: Code +1, Review: QA +1

#819 Add configuration of migration options and nesting on instances and profiles
  src/components/forms/MigrationForm.tsx
  src/components/forms/SecurityPoliciesForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/util/configInheritance.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceEdit.tsx
  src/util/profileEdit.tsx
Labels: Review: Code +1, Review: QA +1

#821 Add link to the authentication setup FAQ from the certificate generation and reuse pages
  src/pages/login/CertificateAdd.tsx
  src/pages/login/CertificateGenerate.tsx
Labels: Review: Code +1, Review: QA +1

#822 [WD-13254] test: network forms
  src/pages/networks/EditNetwork.tsx
  tests/helpers/configuration.ts
  tests/helpers/network.ts
  tests/networks.spec.ts
  tests/projects.spec.ts
Labels: Review: Code +1, Review: QA +1

#823 fix(disk) preserve devices.root.size.state key on instance configuration update
  src/types/device.d.ts
  src/util/formDevices.spec.ts
  src/util/formDevices.tsx
Labels: Review: Code +1, Review: QA +1

#825 fix: publish image from snapshot created in a project that is not the default project
  src/api/images.tsx
  src/sass/_selectable_main_table.scss
  tests/helpers/images.ts
  tests/helpers/instances.ts
  tests/helpers/projects.ts
  tests/helpers/snapshots.ts
  tests/snapshots.spec.ts
Labels: Review: Code +1, Review: QA +1
