Repository canonical/lxd-ui, pull requests merged in 2024-04, with the labels that each got.

#717 Avoid null pointer exception on custom images
  src/pages/images/ImageList.tsx
  src/pages/images/ImageName.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/types/image.d.ts
  src/util/images.tsx
Labels: Review: Code +1, Review: QA +1

#715 Update to vite 5
  package.json
  yarn.lock
Labels: Review: Code +1

#720 Add lxd images server
  src/pages/images/ImageSelector.tsx
Labels: Review: Code +1, Review: QA +1

#721 fix: create instance from custom image
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/types/image.d.ts
  src/util/images.tsx
Labels: Review: Code +1, Review: QA +1

#718 Use fetch all volumes endpoint
  src/api/storage-pools.tsx
  src/context/loadIsoVolumes.tsx
  src/context/useSupportedFeatures.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/StorageVolumes.tsx
Labels: Review: Code +1, Review: QA +1

#725 ci: remove all monaco-editor directories when uploading coverage report bundle
  .github/workflows/coverage.yaml
Labels: Review: Code +1

#728 List minimal images after standard images
  src/pages/images/ImageSelector.tsx
Labels: Review: Code +1, Review: QA +1

#731 Ensure network forward test is stable WD-10196
  tests/helpers/network.ts
Labels: Review: Code +1

#730 feat: update aside panels to use react portal
  src/Root.tsx
  src/components/Panels.tsx
  src/components/SidePanel.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/profiles/ProfileList.tsx
Labels: Review: Code +1, Review: QA needed

#740 chore(code) avoid react imports and add return types
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/pages/projects/forms/ClusterRestrictionForm.tsx
  src/pages/projects/forms/DeviceUsageRestrictionForm.tsx
  src/pages/projects/forms/InstanceRestrictionForm.tsx
  src/pages/projects/forms/NetworkRestrictionForm.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/projects/forms/ProjectResourceLimitsForm.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/types/config.d.ts
  src/util/projectConfigFields.tsx
  src/util/projectEdit.tsx
Labels: Review: Code +1

#739 Avoid flaky instance terminal test
  tests/instances.spec.ts
Labels: Review: Code +1

#738 Add link to iso volumes from image list
  src/pages/images/ImageList.tsx
  src/pages/storage/actions/CustomIsoBtn.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#735 Auto refresh operations WD-10292
  src/context/operationsProvider.tsx
  src/pages/operations/OperationList.tsx
  src/pages/operations/actions/RefreshOperationsBtn.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#733 Add image creation from instance snapshot WD-10293
  src/api/images.tsx
  src/components/forms/SnapshotForm.tsx
  src/context/eventQueue.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/actions/snapshots/CreateImageFromInstanceSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotActions.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotActions.tsx
  src/sass/_toast.scss
  src/types/event.d.ts
  tests/helpers/snapshots.ts
  tests/storage.spec.ts
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#741 Update to v5 WD-10136
  package.json
  yarn.lock
Labels: Review: Code +1

#744 Fix demo: loose deleted files on demo branch WD-10413
  .github/workflows/update_demo.yml
Labels: Review: Code +1

#743 Ensure instance type is derived from image type
  src/pages/images/CustomIsoModal.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/images/actions/SelectImageBtn.tsx
  src/pages/images/actions/UseCustomIsoBtn.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/types/image.d.ts
  src/util/images.tsx
Labels: Review: Code +1, Review: QA +1

#747 fix(instance): add name length check for instance name (creation/edit)
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/sass/_rename_header.scss
  src/util/instances.tsx
Labels: Review: Code +1, Review: QA +1

#752 Use bibyte everywhere and avoid the MB or GB reportings
  src/components/forms/MemoryLimitSelector.tsx
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#754 Remove storage volume detail page and snapshots for custom ISOs
  src/pages/storage/StorageVolumeNameLink.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/actions/CustomStorageVolumeActions.tsx
  src/util/storageVolume.tsx
Labels: Review: Code +1, Review: QA +1

#756 Extend data for error reports
  src/components/ErrorPage.tsx
Labels: Review: Code +1, Review: QA +1

#755 fix architecture filtering on image selection
  src/util/architectures.spec.ts
  src/util/architectures.tsx
Labels: Review: Code +1, Review: QA +1

#760 Ensure instance yaml form updates after saving changed yaml
  src/pages/instances/EditInstance.tsx
Labels: Review: Code +1, Review: QA +1

#758 fix network config for physical and non-managed networks
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/types/config.d.ts
  src/types/network.d.ts
  src/util/networks.tsx
Labels: Review: Code +1, Review: QA +1
