Repository canonical/lxd-ui, pull requests merged in 2024-05, with the labels that each got.

#759 ensure scrolling a vm graphic console is propagated to the parent element
  src/pages/instances/InstanceGraphicConsole.tsx
Labels: Review: Code +1, Review: QA +1

#765 Case insensitive search in image list on instance launch
  src/pages/images/ImageSelector.tsx
Labels: Review: Code +1, Review: QA +1

#762 chore: add tests for permissions
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  HACKING.md
  package.json
  src/util/permissions.spec.ts
  src/util/resourceDetails.spec.ts
  tests/helpers/permission-groups.ts
  tests/helpers/permission-identities.ts
  tests/helpers/permission-idp-groups.ts
  tests/helpers/permissions.ts
  tests/helpers/server.ts
  tests/permission-groups.spec.ts
  tests/permission-identities.spec.ts
  tests/permission-idp-groups.spec.ts
  tests/permissions.spec.ts
Labels: Review: Code +1, Review: QA +1

#764 Update steps to setup ui
  README.md
Labels: Review: Code needed

#772 Fix pool urls
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
Labels: Review: Code +1, Review: QA +1

#775 Fix CI: enforce older version of requests library when installing dotrun
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1

#778 Filter volume snapshots on selecting custom volume
  src/context/loadCustomVolumes.tsx
  src/context/loadIsoVolumes.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
Labels: Review: Code +1, Review: QA +1

#774 Update react components
  package.json
  src/pages/permissions/panels/EditGroupPermissionsPanel.tsx
  src/pages/permissions/panels/GroupSelection.tsx
  src/sass/_empty_state.scss
  yarn.lock
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#776 Automate screenshotting for the readme WD-11363
  .gitignore
  README.md
  tests/helpers/instances.ts
  tests/helpers/profile.ts
  tests/readme-screenshots.spec.ts
Labels: Review: Code +1

#782 fix: fix readme-screenshots.spec.ts to properly skip tests in CI environment
  tests/readme-screenshots.spec.ts
Labels: Review: Code needed
