Repository canonical/lxd-ui, pull requests merged in 2024-08, with the labels that each got.

#826 update: add support for instance_create_start api extension [WD-13645]
  src/context/useSupportedFeatures.tsx
  src/pages/instances/CreateInstance.tsx
Labels: Review: Code +1, Review: QA +1

#827 fix: add type checks in linting script [WD-13573]
  package.json
  src/pages/login/PasswordModal.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/forms/EditVolumeSnapshotForm.tsx
Labels: Review: Code needed

#829 fix: invalidate query cache when creating custom storage volume [WD-13879]
  src/pages/storage/forms/StorageVolumeCreate.tsx
Labels: Review: Code +1, Review: QA +1

#830 fix: adjust copy for project form
  src/pages/projects/forms/ProjectDetailsForm.tsx
Labels: Review: Code needed, Review: QA needed

#847 feat: update wording on create certificate page
  src/pages/login/BrowserImport.tsx
  src/pages/login/CertificateGenerate.tsx
Labels: Review: Code needed

#850 fix: adjust generate certificate page layout
  src/pages/login/CertificateGenerate.tsx
  src/sass/_certificates.scss
Labels: Review: Code +1, Review: QA +1

#843 feat: improve project deletion experience [WD-13431]
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/sass/styles.scss
  src/util/resourceDetails.tsx
  src/util/usedBy.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#852 fix(volume) custom volume cache key needs to include the current project
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/forms/StorageVolumeCreate.tsx
Labels: Review: Code +1, Review: QA +1

#840 feat: bulk migrate instances [WD-13700]
  src/api/instances.tsx
  src/context/instanceLoading.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/MigrateInstanceForm.tsx
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/instances/actions/BulkMigrateInstanceBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/FreezeInstanceBtn.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/sass/_migrate_instance.scss
  src/sass/styles.scss
  src/types/instance.d.ts
  src/util/instanceMigrate.tsx
  src/util/instanceStart.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#831 feat: [WD-13703] add export image
  src/pages/images/ImageList.tsx
  src/pages/images/actions/ExportImageTarballBtn.tsx
Labels: Review: Code needed, Review: QA +1

#833 feat: [WD-13702] Add publish instance
  src/api/images.tsx
  src/components/SelectableMainTable.tsx
  src/pages/images/ImageList.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/CreateImageFromInstanceBtn.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/sass/_instance_detail_page.scss
  tests/publish-instance.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#853 feat: create instance from backup file [WD-13919]
  src/api/instances.tsx
  src/context/toastNotificationProvider.tsx
  src/pages/images/actions/UploadInstanceBtn.tsx
  src/pages/images/actions/UseCustomIsoBtn.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/sass/_forms.scss
  src/sass/_upload_instance_modal.scss
  src/sass/styles.scss
  src/util/instances.tsx
Labels: Review: Code +1, Review: QA +1

#856 feat: [WD-14347] Refactor for create image API
  src/api/images.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
Labels: Review: Code +1, Review: QA needed

#846 feat: enrich permission selector entitlements with descriptions [WD-13431]
  src/api/server.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/types/config.d.ts
  src/util/permissions.spec.ts
  src/util/permissions.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#849 feat: [WD-14036] Duplicate instance (lxc copy)
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/DuplicateInstanceBtn.tsx
  src/pages/instances/actions/UploadInstanceBtn.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/sass/_instance_detail_page.scss
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#848 feat: [WD-13704] Create image from backup file
  src/api/images.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/actions/DownloadImageBtn.tsx
  src/pages/images/actions/UploadImageBtn.tsx
  src/pages/images/actions/forms/UploadImageForm.tsx
  src/sass/_images.scss
  src/sass/_page_header.scss
Labels: Review: Code needed, Review: QA needed

#859 fix: infinite api call loop when duplicating instance
  src/pages/instances/forms/DuplicateInstanceForm.tsx
Labels: Review: Code needed, Review: QA needed

#857 fix(ui) avoid small caps for keys from key value pairs shown on detail page overview
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/InstanceOverviewMetrics.tsx
  src/pages/instances/InstanceOverviewNetworks.tsx
  src/pages/instances/InstanceOverviewProfiles.tsx
  src/pages/networks/NetworkDetailOverview.tsx
  src/pages/profiles/ProfileDetailOverview.tsx
  src/pages/storage/StoragePoolOverview.tsx
  src/pages/storage/StorageUsedBy.tsx
  src/pages/storage/StorageVolumeOverview.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#799 fix(network) show physical managed network state
  src/pages/networks/NetworkDetailOverview.tsx
Labels: Review: Code +1, Review: QA +1

#862 feat: [WD-14391] instance duplication tests
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#860 simpler one click edit mode for edit forms
  src/components/ConfigurationRow.tsx
  src/components/forms/DiskDeviceFormCustom.tsx
  src/components/forms/DiskDeviceFormInherited.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/components/forms/RenameDiskDeviceInput.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StorageVolumeEdit.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/sass/_disk_device_form.scss
  src/sass/_forms.scss
  src/util/instanceEdit.tsx
  tests/devices.spec.ts
  tests/doc-links.spec.ts
  tests/helpers/configuration.ts
  tests/helpers/instances.ts
  tests/helpers/network.ts
  tests/helpers/profile.ts
  tests/helpers/storagePool.ts
  tests/helpers/storageVolume.ts
  tests/networks.spec.ts
  tests/projects.spec.ts
  tests/readme-screenshots.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#864 move yaml switch to the footer of forms and flatten navigation
  src/components/forms/YamlConfirmation.tsx
  src/components/forms/YamlNotification.tsx
  src/components/forms/YamlSwitch.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormMenu.tsx
  src/sass/_forms.scss
  src/sass/_network_form.scss
  src/sass/_storage_pool_form.scss
  tests/devices.spec.ts
  tests/helpers/instances.ts
  tests/helpers/network.ts
  tests/instances.spec.ts
  tests/iso-volumes.spec.ts
  tests/profiles.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#865 Simplify snapshot test
  tests/snapshots.spec.ts
Labels: Review: Code +1

#861 feat: [WD-14389] Combine instance detail page actions
  src/components/RenameHeader.tsx
  src/pages/instances/InstanceDetailActions.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/actions/CreateImageFromInstanceBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/DuplicateInstanceBtn.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/sass/_rename_header.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#868 feat: [WD-14383] Image export upload delete tests
  tests/helpers/images.ts
  tests/helpers/instances.ts
  tests/images.spec.ts
  tests/instances.spec.ts
  tests/publish-instance.spec.ts
Labels: Review: Code +1, Review: QA needed
