Repository canonical/lxd-ui, pull requests merged in 2025-03, with the labels that each got.

#1124 feat: [WD-18263] CMS Storage pool usage
  src/api/storage-pools.tsx
  src/context/useStoragePools.tsx
  src/pages/storage/StoragePoolClusterMember.tsx
  src/pages/storage/StoragePoolOverview.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/pages/storage/StoragePoolSize.tsx
  src/pages/storage/StoragePools.tsx
  src/sass/_meter.scss
  src/sass/_migrate_instance.scss
  src/sass/_scrollable_table.scss
  src/sass/_storage.scss
  src/sass/_storage_detail_overview.scss
  src/types/storage.d.ts
  src/util/storagePool.tsx
Labels: Review: Code +1, Review: QA +1

#1132 Use cla v2
  .github/workflows/pr.yaml
Labels: Review: Code needed

#1130 fix(events): close ws connection on unmount, catch and retry logic
  src/api/images.tsx
  src/api/instance-snapshots.tsx
  src/api/instances.tsx
  src/api/volume-snapshots.tsx
  src/pages/images/actions/BulkDeleteImageBtn.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/actions/InstanceBulkActions.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotBulkDelete.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotBulkDelete.tsx
  src/util/helpers.tsx
  src/util/promises.ts
Labels: Review: Code +1, Review: QA +1

#1135 fix(instance) ensure meters for memory and cpu are positioned in line with text in instance list rows
  src/sass/_instance_list.scss
Labels: Review: Code needed, Review: QA needed

#1134 feat: [WD-19336] Storage volumes permission checks
  src/api/storage-volumes.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/StorageVolumeNameLink.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/actions/CreateVolumeBtn.tsx
  src/pages/storage/actions/DuplicateVolumeBtn.tsx
  src/pages/storage/actions/snapshots/VolumeAddSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeEditSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotActions.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotBulkDelete.tsx
  src/pages/storage/forms/EditStorageVolume.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/entitlements/storage-volumes.tsx
  src/util/storageVolumeEdit.tsx
Labels: Review: Code needed, Review: QA needed

#1131 Show a warning modal for users with restricted permissions that can't read events
  src/api/projects.tsx
  src/components/Navigation.tsx
  src/components/NoProject.tsx
  src/context/useCurrentProject.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/projects/ProjectPermissionWarning.tsx
  src/pages/warnings/WarningList.tsx
  src/util/entitlements/projects.tsx
  tests/helpers/projects.ts
Labels: Review: Code needed, Review: QA needed

#1145 chore introduce is clustered hook to simplify WD-20335
  src/context/useClusterMembers.tsx
  src/context/useIsClustered.tsx
  src/pages/cluster/ClusterList.tsx
  src/pages/cluster/ClusterMemberSelector.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSearchFilter.tsx
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceLocationSelect.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/settings/SettingForm.tsx
  src/pages/storage/StoragePoolOverview.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/pages/storage/StoragePoolSize.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/forms/StoragePoolFormZFS.tsx
  src/util/instanceLocation.tsx
Labels: Review: Code needed

#1141 fix network forward success message
  src/api/network-forwards.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/actions/DeleteNetworkForwardBtn.tsx
  src/util/helpers.tsx
  tests/helpers/network.ts
Labels: Review: Code needed, Review: QA needed

#1138 Show identity id instead of name, when the name is empty
  src/context/useLoggedInUser.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/actions/EditIdentityGroupsBtn.tsx
  src/pages/permissions/panels/EditGroupIdentitiesPanel.tsx
  src/pages/permissions/panels/EditIdentitiesForm.tsx
  src/pages/permissions/panels/GroupOrIdentityChangesTable.tsx
  src/util/permissionGroups.tsx
  src/util/permissionIdentities.tsx
  src/util/permissions.tsx
Labels: Review: Code needed, Review: QA needed

#1150 Update vite and vitest
  package.json
  yarn.lock
Labels: Review: Code needed

#1148 Add security.csm configuration to profiles and instances
  src/components/forms/SecurityPoliciesForm.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceEdit.tsx
Labels: Review: Code needed, Review: QA needed

#1160 Use link instead of anchor to avoid full page load
  src/pages/login/Login.tsx
  src/pages/storage/StoragePoolDetail.tsx
Labels: Review: Code needed, Review: QA needed

#1157 Avoid infinite render loop on empty image list
  src/pages/images/ImageSelector.tsx
Labels: Review: Code needed, Review: QA needed

#1158 Detect custom image for operation relating to an image in a non-default project
  src/types/operation.d.ts
  src/util/operations.spec.ts
  src/util/operations.tsx
Labels: Review: Code needed

#1159 Snapshot fixes
  src/components/forms/SnapshotForm.tsx
  src/pages/instances/actions/snapshots/InstanceConfigureSnapshotModal.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotModal.tsx
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#1166 feat(ssh) design fixes for ssh keys
  src/components/forms/SshKeyAddModal.tsx
  src/components/forms/SshKeyForm.tsx
  src/sass/_ssh_key_form.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1142 fix custom iso volumes in clusters
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/forms/InstanceLocationSelect.tsx
Labels: Review: Code +1, Review: QA +1
