Repository canonical/lxd-ui, pull requests merged in 2025-05, with the labels that each got.

#1217 fix(modals) ensure errors from modals are visible
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
  src/pages/instances/forms/ExportInstanceModal.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/forms/CopyVolumeForm.tsx
  src/pages/storage/forms/CreateVolumeSnapshotForm.tsx
  src/pages/storage/forms/EditVolumeSnapshotForm.tsx
  src/util/instanceMigration.tsx
Labels: Review: Code needed, Review: QA needed

#1222 fix(instance) remove border radius from selected actions
  src/sass/_instance_list.scss
Labels: Review: QA needed, Docs needed

#1238 chore(deps) update react components and imports
  package.json
  src/components/ToastNotification.tsx
  src/components/ToastNotificationList.tsx
  src/context/toastNotificationProvider.tsx
  src/sass/_scrollable_table.scss
  yarn.lock
Labels: Review: Code needed

#1223 feat(export) add help text to hint no compression is faster
  src/pages/instances/forms/ExportInstanceModal.tsx
Labels: Review: Code +1, Review: QA +1

#1233 fix(forms) disable submit buttons when form is submitting. fixes #1227
  src/components/RenameHeader.tsx
  src/components/forms/FormSubmitBtn.tsx
  src/components/forms/SnapshotForm.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/images/actions/forms/UploadImageForm.tsx
  src/pages/instances/forms/CopyInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceForm.tsx
  src/pages/instances/forms/CreateImageFromInstanceSnapshotForm.tsx
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/pages/instances/forms/UploadInstanceBackupFileForm.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/permissions/panels/CreateGroupPanel.tsx
  src/pages/permissions/panels/CreateIdpGroupPanel.tsx
  src/pages/permissions/panels/CreateTLSIdentityPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/forms/CopyVolumeForm.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
Labels: Review: Code +1, Review: QA +1

#1213 fix(instance) handle instances in status Ready correctly
  src/pages/instances/InstanceConsole.tsx
  src/pages/instances/InstanceGraphicConsole.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
  src/pages/instances/actions/FreezeInstanceBtn.tsx
  src/util/instanceStatus.tsx
Labels: Review: Design +1, Review: Code +1

#1247 fix(instance) open instance panel reliably on non-default projects
  src/util/usePanelParams.tsx
Labels: Review: Code needed, Review: QA needed

#1220 feat: [WD-21812] Refactor Migrate wording to Move
  src/pages/instances/MigrateInstanceModal.tsx
  src/util/instanceMigration.tsx
  tests/helpers/instances.ts
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#1252 feat(warnings) allow bulk delete of server warnings
  src/api/warnings.tsx
  src/pages/warnings/WarningList.tsx
  src/pages/warnings/actions/BulkDeleteWarningBtn.tsx
  src/sass/_warnings_table.scss
  src/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#1254 fix(instance) make instance table responsive
  src/sass/_scrollable_table.scss
Labels: Review: Code needed, Review: QA needed

#1255 fix(images) show local images immediately when filtering cached images
  src/pages/images/ImageSelector.tsx
Labels: Review: Code needed, Review: QA needed

#1249 fix(instance) disable cluster member and cluster group targeting
  src/pages/instances/forms/InstanceLocationSelect.tsx
Labels: Review: Code +1, Review: QA +1

#1239 fix(translation) ensure app does not crash on using chrome translation
  src/components/ConfigurationRow.tsx
  src/components/SidePanel.tsx
  src/components/ToastNotification.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/instances/InstanceDetailPanelContent.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/InstanceOverviewMetrics.tsx
  src/pages/instances/InstanceUsageCpu.tsx
  src/pages/instances/MigrateInstanceModal.tsx
  src/pages/networks/forms/IpAddress.tsx
  src/pages/networks/forms/NetworkAcls.tsx
  src/pages/networks/forms/NetworkDescriptionField.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/pages/permissions/panels/CreateGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
Labels: Review: Code +1, Review: QA +1

#1258 fix(network) remove 'range' from ipv4 and ipv6 address labels in network form
  src/pages/networks/forms/NetworkFormMain.tsx
Labels: Review: Code +1, Review: QA +1

#1216 Simplify api calls
  src/api/auth-groups.tsx
  src/api/auth-identities.tsx
  src/api/auth-idp-groups.tsx
  src/api/auth-permissions.tsx
  src/api/certificates.tsx
  src/api/cluster.tsx
  src/api/images.tsx
  src/api/instance-snapshots.tsx
  src/api/instances.tsx
  src/api/metrics.tsx
  src/api/network-acls.tsx
  src/api/network-forwards.tsx
  src/api/networks.tsx
  src/api/operations.tsx
  src/api/profiles.tsx
  src/api/projects.tsx
  src/api/server.tsx
  src/api/storage-pools.tsx
  src/api/storage-volumes.tsx
  src/api/volume-snapshots.tsx
  src/api/warnings.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
Labels: Review: Code needed, Review: QA needed

#1262 fix(export) update help text for instance export expiration
  src/pages/instances/forms/ExportInstanceModal.tsx
Labels: Review: Code needed, Review: QA needed

#1260 chore(pr) check for non-ascii characters in code files
  .github/workflows/pr.yaml
  src/pages/login/BrowserImport.tsx
  src/pages/login/CertificateAdd.tsx
  src/pages/permissions/CreateIdentityModal.tsx
  src/pages/permissions/panels/LoggedInUserNotification.tsx
  tests/operations.spec.ts
Labels: Review: Code needed

#1250 feat: [WD-22116] Adds Ceph Object storage driver
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormCephObject.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/storageOptions.tsx
  src/util/storagePool.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Code +1, Review: QA +1

#1265 fix(identities) avoid closing tab on deleting identity
  src/pages/permissions/actions/BulkDeleteIdentitiesBtn.tsx
Labels: Review: Code needed, Review: QA needed

#1264 fix(warnings) rely on can_edit server permission for deleting warnings
  src/api/warnings.tsx
  src/pages/warnings/WarningList.tsx
  src/pages/warnings/actions/BulkDeleteWarningBtn.tsx
  src/util/entitlements/warnings.tsx
Labels: Review: Code needed, Review: QA needed

#1268 fix(instance) ensure only one instance is in loading state
  src/components/forms/BootForm.tsx
  src/components/forms/CloudInitForm.tsx
  src/components/forms/InstanceSnapshotsForm.tsx
  src/components/forms/MigrationForm.tsx
  src/components/forms/ResourceLimitsForm.tsx
  src/components/forms/SecurityPoliciesForm.tsx
  src/context/instanceLoading.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/actions/InstanceBulkAction.tsx
  src/pages/instances/actions/InstanceBulkActions.tsx
  src/util/configInheritance.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceMigration.tsx
  src/util/instances.tsx
Labels: Review: Code needed, Review: QA needed

#1274 fix(instance) column toggle to allow deselcting columns that are hidden
  src/components/TableColumnsSelect.tsx
  src/pages/instances/InstanceList.tsx
  src/sass/_instance_list.scss
  src/util/instanceTable.tsx
Labels: Review: Code +1, Review: QA +1

#1276 fix(responsive) use dvh instead of vh for better mobile experience
  src/components/ScrollableContainer.tsx
  src/components/ScrollableTable.tsx
  src/components/ToastNotificationList.tsx
  src/sass/_aside.scss
  src/sass/_empty_state.scss
  src/sass/_forms.scss
  src/sass/_network_form.scss
  src/sass/_pattern_terminal.scss
  src/sass/_scrollable_table.scss
  src/sass/_side_panel.scss
  src/sass/_toast.scss
  src/util/updateMaxHeight.tsx
Labels: Review: Code +1, Review: QA +1
