Repository canonical/lxd-ui, pull requests merged in 2025-06, with the labels that each got.

#1281 fix(volume) hide cluster member selector on volume edit if we are not in a cluster environment
  src/pages/storage/forms/StorageVolumeFormMain.tsx
Labels: Review: Code needed, Review: QA needed

#1285 fix(loading) disable submit buttons while loading. fixes #1283
  src/pages/cluster/actions/DeleteClusterGroupBtn.tsx
  src/pages/cluster/actions/EvacuateClusterMemberBtn.tsx
  src/pages/cluster/actions/RestoreClusterMemberBtn.tsx
  src/pages/images/actions/DownloadImageBtn.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/InstanceConsole.tsx
  src/pages/instances/actions/AttachIsoBtn.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/FreezeInstanceBtn.tsx
  src/pages/instances/actions/InstanceBulkAction.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/pages/instances/actions/RestartInstanceBtn.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/pages/instances/forms/ExportInstanceModal.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkAcl.tsx
  src/pages/networks/actions/DeleteNetworkAclBtn.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/networks/actions/DeleteNetworkForwardBtn.tsx
  src/pages/operations/actions/CancelOperationBtn.tsx
  src/pages/operations/actions/RefreshOperationsBtn.tsx
  src/pages/permissions/actions/DeleteGroupModal.tsx
  src/pages/permissions/actions/DeleteIdentityBtn.tsx
  src/pages/permissions/actions/GroupSelectionActions.tsx
  src/pages/permissions/panels/EditIdpGroupPanel.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/HostPathDeviceModal.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/actions/DeleteStorageVolumeBtn.tsx
  src/pages/storage/forms/ExportVolumeModal.tsx
  src/pages/warnings/actions/BulkDeleteWarningBtn.tsx
Labels: Review: Code +1, Review: QA +1

#1287 chore(tics) remove compiler warnings
  src/components/forms/GPUDeviceForm.tsx
  src/components/forms/OtherDeviceForm.tsx
  src/components/forms/ProxyDeviceForm.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/networks/NetworkTopology.tsx
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/PermissionIdpGroups.tsx
Labels: Review: Code +1

#1298 chore(docs) create screenshots for the documentation with a test suite
  tests/docs-screenshots.spec.ts
Labels: Review: Code +1, Review: QA +1

#1302 Visual improvements
  package.json
  src/sass/_instance_list.scss
  src/sass/_snapshots.scss
  src/sass/_storage.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1301 chore(volume) add volume upload test
  .gitignore
  src/pages/storage/forms/UploadVolumeBackupFileForm.tsx
  tests/helpers/storageVolume.ts
  tests/storage.spec.ts
Labels: Review: Code needed, Review: QA +1

#1306 fix(operations) ensure date wraps well on small screens
  src/pages/operations/OperationList.tsx
  src/pages/operations/actions/RefreshOperationsBtn.tsx
  src/sass/_operation_list.scss
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#1305 feat: [WD-22810] Create + Edit Bucket E2E Tests
  tests/helpers/storageBucket.ts
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#1312 chore(panels) remove dead panel code
  src/util/usePanelParams.tsx
Labels: Review: Code +1

#1313 chore(readme) move screenshots to assets server to avoid loading problems with github hosted images
  README.md
Labels: Review: Code +1

#1316 feat(network) add bridge.external_interfaces config option
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/util/networkForm.tsx
  src/util/networks.tsx
Labels: Review: Code +1, Review: QA +1

#1324 feat(network) add network lease tab to network detail page
  src/api/network-leases.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkLeases.tsx
  src/types/network.d.ts
  src/util/projects.tsx
  src/util/queryKeys.tsx
Labels: Review: Code +1, Review: QA +1

#1325 feat(network) add ipam page
  src/App.tsx
  src/api/networks.tsx
  src/components/Navigation.tsx
  src/components/ResourceIcon.tsx
  src/pages/networks/NetworkIPAM.tsx
  src/sass/_network_ipam.scss
  src/sass/styles.scss
  src/types/network.d.ts
  src/util/projects.tsx
  src/util/queryKeys.tsx
  src/util/resourceDetails.tsx
  src/util/usedBy.tsx
Labels: Review: Code +1, Review: QA +1

#1326 fix(settings) surface error on loading cluster member specific values in server settings page
  src/context/useSettings.tsx
  src/pages/settings/Settings.tsx
Labels: Review: Code +1, Review: QA +1

#1327 feat(network) make bridge.external_interfaces node specific in a clustered setup
  src/api/networks.tsx
  src/components/ConfigurationRow.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/ClusteredBridgeInterfaceInput.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/util/networkForm.tsx
Labels: Review: Code +1, Review: QA +1

#1342 feat(instance) show mac address in side panel.
  src/components/NetworkListTable.tsx
  src/pages/instances/InstaceMACAddresses.tsx
  src/pages/instances/InstanceDetailPanelContent.tsx
  src/pages/networks/NetworkLeases.tsx
Labels: Review: Code +1, Review: QA +1
