Repository canonical/lxd-ui, pull requests merged in 2025-07, with the labels that each got.

#1346 feat(certificate) detect browser and select correct tab automatically
  src/pages/login/BrowserImport.tsx
Labels: Review: Code needed

#1330 chore(tests) update oidc config
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  tests/scripts/setup_test
Labels: Review: Code +1

#1322 fix(settings) use metadata api to determine clustered server settings
  src/pages/settings/SettingForm.tsx
Labels: Review: Code needed, Review: QA needed

#1353 fix(groups) make permission selectors responsive
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/sass/_permission_groups.scss
Labels: Review: Code needed, Review: QA needed

#1355 chore(css) remove unused toast scss, this is now upstreamed in react components
  src/sass/_toast.scss
  src/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1356 chore(network) add network tests
  tests/helpers/network.ts
Labels: Review: Code +1

#1368 feat(acl) add download acl log button
  src/api/network-acls.tsx
  src/pages/networks/NetworkAclDetailHeader.tsx
  src/pages/networks/actions/DownloadNetworkAclLogBtn.tsx
Labels: Review: Code +1

#1363 feat(network) add macvlan and sriov network types WD-23498
  src/api/networks.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/NetworkAclDetailHeader.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkForwardCount.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkTopology.tsx
  src/pages/networks/actions/DownloadNetworkAclLogsBtn.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/pages/networks/forms/NetworkFormDns.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormIpv6.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
  src/pages/networks/forms/NetworkGVRPField.tsx
  src/pages/networks/forms/NetworkMTUField.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/networks/forms/NetworkVlanField.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/types/network.d.ts
  src/util/networkForm.tsx
  src/util/networks.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#1369 feat(operations) show instances as a chip with resource link in operations page
  src/pages/operations/OperationInstanceName.tsx
Labels: Review: Code needed, Review: QA needed

#1371 fix(auth-group) pending permission or identity edits in side panel should persist a tab change
  src/api/auth-groups.tsx
  src/api/auth-identities.tsx
Labels: Review: Code +1, Review: QA +1

#1367 fix(auth) show errors on loading authentication. fixes #1366
  src/App.tsx
  src/context/auth.tsx
Labels: Review: Code needed

#1372 fix: [WD-22935] Add hook for small screens
  src/components/Navigation.tsx
  src/components/OperationStatus.tsx
  src/context/menuCollapsed.tsx
  src/context/useIsScreenBelow.tsx
  src/context/useSmallScreen.tsx
  src/pages/images/actions/UploadCustomIsoBtn.tsx
  src/pages/images/actions/UploadImageBtn.tsx
  src/pages/instances/InstanceDetailActions.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/actions/DeleteNetworkAclBtn.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/networks/actions/DownloadNetworkAclLogsBtn.tsx
  src/pages/operations/actions/RefreshOperationsBtn.tsx
  src/pages/permissions/CreateTlsIdentityBtn.tsx
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/PermissionIdpGroups.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/StorageVolumeDetailActions.tsx
  src/pages/storage/actions/CreateStorageBucketBtn.tsx
  src/pages/storage/actions/CreateStorageBucketKeyBtn.tsx
  src/pages/storage/actions/CreateStoragePoolBtn.tsx
  src/pages/storage/actions/CreateVolumeBtn.tsx
  src/pages/storage/actions/CustomIsoBtn.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/actions/StorageBucketActions.tsx
Labels: Review: Code +1, Review: QA +1

#1378 fix(panels) ensure side panels for instances and profiles are sticky when scrolling
  src/pages/instances/InstanceDetailPanel.tsx
  src/pages/profiles/ProfileDetailPanel.tsx
Labels: Review: Code needed, Review: QA needed

#1380 feat(groups) sort identities that are selected to the top when editing an auth group
  src/pages/permissions/panels/EditGroupIdentitiesPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditIdentitiesForm.tsx
  src/util/permissionIdentities.tsx
Labels: Review: Code needed, Review: QA needed

#1386 fix(listener) rely on upstream listener hook
  src/components/ErrorPage.tsx
  src/components/Navigation.tsx
  src/components/ScrollableContainer.tsx
  src/components/ScrollableTable.tsx
  src/components/SelectableMainTable.tsx
  src/components/StatusBar.tsx
  src/components/forms/FormSubmitBtn.tsx
  src/components/forms/ScrollableConfigurationTable.tsx
  src/components/forms/YamlForm.tsx
  src/context/menuCollapsed.tsx
  src/context/useIsScreenBelow.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/InstanceGraphicConsole.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverview.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
  src/pages/instances/TerminalPayloadForm.tsx
  src/pages/instances/forms/InstanceFormMenu.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
  src/pages/permissions/panels/GroupOrIdentityChangesTable.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/ProfileDetailOverview.tsx
  src/pages/profiles/forms/ProfileFormMenu.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/StoragePoolOverview.tsx
  src/pages/storage/StorageVolumeOverview.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormMenu.tsx
  src/util/useEditHistory.tsx
  src/util/useEventListener.ts
Labels: Review: Code needed

#1405 fix(vm) shortcuts sent to vms should release modifiers with a slight delay
  src/lib/spice/src/inputs.js
Labels: Review: Code needed
