Repository canonical/lxd-ui, pull requests merged in 2025-04, with the labels that each got.

#1151 Ensure instances in foreign projects are shown with project in the network topology. Avoid mixup of projects for instance metrics.
  src/pages/networks/NetworkTopology.tsx
  src/util/formChangeCount.spec.ts
  src/util/formChangeCount.tsx
  src/util/metricSelectors.tsx
Labels: Review: Code +1, Review: QA +1

#1165 network forwards for bridged networks in clustered backends
  src/App.tsx
  src/api/network-forwards.tsx
  src/pages/cluster/ClusterMemberSelector.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/NetworkForwardCount.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/forms/NetworkForwardForm.tsx
Labels: Review: Code needed, Review: QA needed

#1171 feat(acl) add network acl management
  src/App.tsx
  src/api/network-acls.tsx
  src/api/projects.tsx
  src/components/ConfigurationRow.tsx
  src/components/NavAccordion.tsx
  src/components/Navigation.tsx
  src/components/ResourceIcon.tsx
  src/context/useNetworkAcls.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkAcl.tsx
  src/pages/networks/NetworkAclDetail.tsx
  src/pages/networks/NetworkAclDetailHeader.tsx
  src/pages/networks/NetworkAclList.tsx
  src/pages/networks/NetworkAclUsedBy.tsx
  src/pages/networks/actions/DeleteNetworkAclBtn.tsx
  src/pages/networks/forms/EditNetworkAcl.tsx
  src/pages/networks/forms/NetworkAclForm.tsx
  src/pages/networks/forms/NetworkAclRuleModal.tsx
  src/pages/networks/forms/NetworkAclRuleTable.tsx
  src/pages/networks/forms/NetworkAclSelector.tsx
  src/pages/networks/forms/NetworkAcls.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/sass/_forms.scss
  src/sass/styles.scss
  src/types/network.d.ts
  src/util/configInheritance.tsx
  src/util/entitlements/network-acls.tsx
  src/util/entitlements/projects.tsx
  src/util/helpers.tsx
  src/util/networkForm.tsx
  src/util/networks.tsx
  src/util/queryKeys.tsx
  src/util/resourceDetails.spec.ts
  src/util/resourceDetails.tsx
  tests/helpers/network-acls.ts
  tests/helpers/network.ts
  tests/network-acls.spec.ts
  tests/networks.spec.ts
Labels: Review: Code +1, Review: QA needed

#1172 feat(permissions) always show permissions in side navigation if lxd supports it
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  CONTRIBUTING.md
  src/components/Navigation.tsx
  src/pages/settings/Settings.tsx
  src/util/permissions.tsx
Labels: Review: Code needed, Review: QA needed

#1174 fix(group) allow to add permissions when creating a group
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  tests/helpers/permission-groups.ts
  tests/permission-groups.spec.ts
Labels: Review: Code needed, Review: QA needed

#1176 fix(volumes) add cluster member selector for volume form
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormMain.tsx
  src/util/hasMemberLocalVolumes.tsx
  src/util/storageVolumeEdit.tsx
Labels: Review: Code +1, Review: QA +1

#1185 fix(project) retain custom project selection on browsing pages for all projects
  src/context/useCurrentProject.tsx
  src/pages/projects/ProjectPermissionWarning.tsx
  tests/helpers/projects.ts
  tests/projects.spec.ts
Labels: Review: Code +1, Review: QA +1

#1198 fix(test) ensure project test is setting a valid cluster group targeting value
  tests/projects.spec.ts
Labels: Review: Code needed

#1186 Fix instance validation on duplication and create from snapshot, remove stateful duplication field
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/util/instances.tsx
Labels: Review: Code needed, Review: QA needed

#1199 fix(permissions) add titles to group and permission selection side panels
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/pages/permissions/panels/GroupSelection.tsx
Labels: Review: Code needed, Review: QA needed

#1202 fix(forms) show browser warning when leaving an edit form with pending changes
  src/components/forms/FormSubmitBtn.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/forms/EditNetworkAcl.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/projects/EditProject.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/EditStorageVolume.tsx
Labels: Review: Code needed, Review: QA needed

#1201 fix(groups) fix a bug when opening the group edit for an identity and navigating forwards and backwards
  src/pages/permissions/panels/GroupSelection.tsx
Labels: Review: Code needed, Review: QA needed

#1200 fix(instances) disable ssh key buttons for users without edit instance permission
  src/components/forms/SshKeyForm.tsx
  src/pages/instances/forms/EditInstanceDetails.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
Labels: Review: Code needed, Review: QA needed

#1182 feat: [WD-20438] Select network on project creation
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/forms/NetworkSelector.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/util/helpers.tsx
  src/util/projectEdit.tsx
  tests/helpers/projects.ts
  tests/projects.spec.ts
Labels: Review: Code +1, Review: QA +1

#1210 fix(router) update react router to resolve security issue
  package.json
  yarn.lock
Labels: Review: Code needed

#1211 chore(permissions) add permissions to all workflows
  .github/workflows/coverage.yaml
  .github/workflows/sbom_generation.yaml
  .github/workflows/update_demo.yml
Labels: Review: Code needed

#1206 fix(permission) avoid panels from rendering a pending 0 above main content, simplify
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/PermissionIdpGroups.tsx
  src/pages/permissions/panels/CreateIdpGroupPanel.tsx
  src/pages/permissions/panels/EditIdpGroupPanel.tsx
Labels: Review: Code needed, Review: QA needed

#1208 feat(instance) allow configure instance export
  src/api/instances.tsx
  src/context/useSupportedFeatures.tsx
  src/pages/instances/actions/ExportInstanceBtn.tsx
  src/pages/instances/forms/ExportInstanceModal.tsx
  src/sass/styles.scss
  src/types/server.d.ts
  tests/instances.spec.ts
Labels: Review: Code +1, Review: QA +1

#1212 chore(ClusterMemberSelector) remove duplicate and confusing setMember callback
  src/pages/cluster/ClusterMemberSelector.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
Labels: Review: Code +1

#1209 feat: [WD-15524] Add target member selection for volume duplication
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/util/storageOptions.tsx
Labels: Review: Code +1, Review: QA +1

#1214 feat: Refactor Duplicate -> Copy for Storage Volumes and Instances
  src/api/storage-volumes.tsx
  src/pages/instances/InstanceDetailActions.tsx
  src/pages/instances/actions/CopyInstanceBtn.tsx
  src/pages/instances/forms/CopyInstanceForm.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/actions/CopyVolumeBtn.tsx
  src/pages/storage/forms/CopyVolumeForm.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
  src/sass/styles.scss
  src/util/instances.tsx
  src/util/storageVolume.tsx
  tests/helpers/storageVolume.ts
  tests/instances.spec.ts
  tests/storage.spec.ts
Labels: Review: Code +1, Review: QA +1

#1204 feat(metrics) show all disk metrics and label main disk metric to root disk
  src/Root.tsx
  src/context/metricHistory.tsx
  src/context/useMetrics.tsx
  src/pages/instances/InstanceDisk.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverviewMetrics.tsx
  src/pages/instances/InstanceUsageCpu.tsx
  src/pages/instances/InstanceUsageFilesystem.tsx
  src/pages/instances/InstanceUsageMainMemory.tsx
  src/pages/instances/InstanceUsageMemory.tsx
  src/pages/instances/InstanceUsageRootFilesystem.tsx
  src/sass/_instance_detail_overview.scss
  src/types/metrics.d.ts
  src/util/instanceTable.tsx
  src/util/metricSelectors.spec.ts
  src/util/metricSelectors.tsx
Labels: Review: Code needed, Review: QA needed
