Repository canonical/lxd-ui, pull requests merged in 2025-02, with the labels that each got.

#1088 Avoid memory leak on uploading external instance files
  src/util/uploadExternalFormatFile.tsx
Labels: Review: Code needed, Review: QA needed

#1089 fix: prevent the instance file upload modal from closing when clicking on the backdrop
  src/pages/instances/forms/UploadInstanceFileModal.tsx
Labels: Review: Code +1, Review: QA +1

#1083 Take project resource limits into account for available limits
  src/components/forms/CpuLimitInput.tsx
  src/components/forms/CpuLimitSelector.tsx
  src/components/forms/DiskSizeSelector.tsx
  src/components/forms/MemoryLimitAvailable.tsx
  src/components/forms/MemoryLimitSelector.tsx
  src/pages/projects/forms/ProjectResourceLimitsForm.tsx
  src/util/limits.tsx
Labels: Review: Code +1, Review: QA +1

#1080 feat: [WD-18674] CMS Fields - ZFS.Poolname
  src/api/storage-pools.tsx
  src/components/forms/ClusterSpecificInput.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/forms/ClusteredZfsNameSelector.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormZFS.tsx
  src/sass/_cluster_specific_input.scss
  src/util/storagePoolForm.tsx
Labels: Review: Design needed, Review: Code needed, Review: QA needed

#1096 fix: setup lxd with group "lxd" in GH actions
  .github/workflows/pr.yaml
  tests/login.spec.ts
Labels: Review: Code needed

#1091 chore: update react to v19
  package.json
  src/components/ConfigurationRow.tsx
  src/components/forms/SelectGPUBtn.tsx
  src/components/forms/YamlSwitch.tsx
  src/pages/images/actions/SelectImageBtn.tsx
  src/pages/images/actions/UploadCustomIsoBtn.tsx
  src/pages/images/actions/UploadImageBtn.tsx
  src/pages/images/actions/UseCustomIsoBtn.tsx
  src/pages/instances/actions/AttachIsoBtn.tsx
  src/pages/instances/actions/CreateImageFromInstanceBtn.tsx
  src/pages/instances/actions/DuplicateInstanceBtn.tsx
  src/pages/instances/actions/MigrateInstanceBtn.tsx
  src/pages/instances/actions/UploadInstanceFileBtn.tsx
  src/pages/instances/actions/snapshots/CreateImageFromInstanceSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/CreateInstanceFromSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/InstanceAddSnapshotBtn.tsx
  src/pages/instances/actions/snapshots/InstanceConfigureSnapshotsBtn.tsx
  src/pages/instances/actions/snapshots/InstanceEditSnapshotBtn.tsx
  src/pages/permissions/CreateTlsIdentityBtn.tsx
  src/pages/permissions/actions/DeleteIdpGroupBtn.tsx
  src/pages/permissions/actions/GroupActions.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/pages/storage/AttachDiskDeviceBtn.tsx
  src/pages/storage/CustomVolumeSelectBtn.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/actions/DuplicateVolumeBtn.tsx
  src/pages/storage/actions/snapshots/VolumeAddSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotBtn.tsx
  src/pages/storage/actions/snapshots/VolumeEditSnapshotBtn.tsx
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#1074 feat: [WD-17724] CMS Storage Pool size field
  src/api/storage-pools.tsx
  src/components/forms/ClusteredDiskSizeSelector.tsx
  src/components/forms/DiskSizeSelector.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/ClusteredSourceSelector.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/util/storagePoolForm.tsx
  tests/storage.spec.ts
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#1104 fix: fix network failing e2e tests
  tests/helpers/network.ts
Labels: Review: Code +1

#1098 fix: align react types for yarn.lock
  package.json
  src/components/ProtectedRoute.tsx
  src/components/TableColumnsSelect.tsx
  src/components/forms/SnapshotForm.tsx
  src/pages/cluster/ClusterGroupLoader.tsx
  src/pages/cluster/ClusterGroupSelector.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/forms/CreateInstanceSnapshotForm.tsx
  src/pages/permissions/panels/GroupOrIdentityChangesTable.tsx
  src/pages/projects/ProjectLoader.tsx
  src/pages/projects/ProjectSelector.tsx
  src/pages/projects/ProjectSelectorList.tsx
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#1106 Remove arbitrary fields from the generated cert
  src/util/certificate.tsx
Labels: Review: Code needed, Review: QA needed

#1100 feat: restricted permissions for image actions [WD-18905]
  src/Root.tsx
  src/api/images.tsx
  src/api/projects.tsx
  src/components/Logo.tsx
  src/components/Navigation.tsx
  src/components/UsedByItem.tsx
  src/components/forms/CpuLimitSelector.tsx
  src/components/forms/InstanceSnapshotsForm.tsx
  src/components/forms/MemoryLimitSelector.tsx
  src/context/auth.tsx
  src/context/useCurrentProject.tsx
  src/context/useImages.tsx
  src/context/useProjects.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/images/actions/CreateInstanceFromImageBtn.tsx
  src/pages/images/actions/DeleteImageBtn.tsx
  src/pages/images/actions/UploadImageBtn.tsx
  src/pages/images/actions/forms/UploadImageForm.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/pages/instances/forms/UploadInstanceBackupFileForm.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/pages/profiles/ProfileDetail.tsx
  src/pages/profiles/ProfileDetailPanel.tsx
  src/pages/profiles/ProfileInstances.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/projects/ProjectConfiguration.tsx
  src/pages/projects/ProjectLoader.tsx
  src/pages/projects/ProjectSelectTable.tsx
  src/pages/projects/ProjectSelector.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/StorageVolumeNameLink.tsx
  src/pages/storage/StorageVolumeSize.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/CustomStorageVolumeActions.tsx
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/pages/storage/forms/StorageVolumeFormSnapshots.tsx
  src/types/image.d.ts
  src/types/project.d.ts
  src/util/entitlements/images.tsx
  src/util/entitlements/projects.tsx
Labels: Review: Code +1, Review: QA +1

#1107 Ensure the size is unset, when selecting a storage pool driver without it, fix network form validation
  src/api/storage-pools.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/util/storagePool.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Code needed, Review: Code +1, Review: QA +1

#1109 Ensure to fetch instance metrics from the right cluster member
  src/api/metrics.tsx
  src/context/useMetrics.tsx
  src/pages/instances/InstanceDisk.tsx
  src/pages/instances/InstanceOverviewMetrics.tsx
  src/pages/instances/InstanceUsageMemory.tsx
  src/util/entitlements/server.tsx
Labels: Review: Code needed, Review: QA +1

#1108 Ensure the creating instances are displayed with the correct column width and span in a clustered backend
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#1112 Add hover text to instance metrics, surfacing details about cached memory and disk size
  src/components/Meter.tsx
  src/pages/instances/InstanceDisk.tsx
  src/pages/instances/InstanceUsageMemory.tsx
Labels: Review: Code +1, Review: QA +1

#1117 fix: create instance from snapshot in a different project when instance project is restricted
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
Labels: Review: Code +1, Review: QA needed

#1114 feat: restricted permissions for networks [WD-18903]
  src/api/networks.tsx
  src/api/projects.tsx
  src/components/ClusterSpecificSelect.tsx
  src/components/FormEditButton.tsx
  src/components/NetworkListTable.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/components/forms/YamlForm.tsx
  src/context/useNetworks.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkDetailHeader.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/NetworkTopology.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/networks/actions/DeleteNetworkForwardBtn.tsx
  src/pages/networks/forms/NetworkDescriptionField.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/types/network.d.ts
  src/util/entitlements/networks.tsx
  src/util/entitlements/projects.tsx
  src/util/networkForm.tsx
Labels: Review: Code +1, Review: QA +1

#1116 feat: restricted permissions for profiles [WD-18904]
  src/api/images.tsx
  src/api/instances.tsx
  src/api/profiles.tsx
  src/api/projects.tsx
  src/components/forms/CpuLimitInput.tsx
  src/components/forms/DiskDeviceForm.tsx
  src/components/forms/DiskDeviceFormRoot.tsx
  src/components/forms/GPUDeviceForm.tsx
  src/components/forms/MemoryLimitAvailable.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/components/forms/OtherDeviceForm.tsx
  src/components/forms/ProxyDeviceForm.tsx
  src/context/useProfiles.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/InstanceOverviewProfiles.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/ProfileDetail.tsx
  src/pages/profiles/ProfileDetailHeader.tsx
  src/pages/profiles/ProfileDetailPanel.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/ProfileSelector.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/profiles/forms/ProfileDetailsForm.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/types/profile.d.ts
  src/util/configInheritance.tsx
  src/util/entitlements/api.tsx
  src/util/entitlements/instances.tsx
  src/util/entitlements/profiles.tsx
  src/util/entitlements/projects.tsx
  src/util/instanceEdit.tsx
Labels: Review: Code +1, Review: QA +1

#1097 feat: [WD-19015] CMS Server Config for maas.machine
  src/api/server.tsx
  src/components/forms/ClusterSpecificInput.tsx
  src/context/useSettings.tsx
  src/pages/settings/ClusteredSettingFormInput.tsx
  src/pages/settings/SettingForm.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/forms/ClusteredSourceSelector.tsx
  src/sass/_settings_page.scss
  src/types/server.d.ts
Labels: Review: Code +1, Review: QA +1

#1115 fix: improve e2e tests flakiness
  tests/helpers/instancePanel.ts
  tests/helpers/network.ts
  tests/helpers/projects.ts
  tests/images.spec.ts
Labels: Review: Code +1, Review: QA +1

#1111 feat: restricted permissions for storage pool [WD-19339]
  src/api/networks.tsx
  src/api/storage-pools.tsx
  src/components/forms/ClusterSpecificInput.tsx
  src/components/forms/ClusteredDiskSizeSelector.tsx
  src/components/forms/DiskDeviceForm.tsx
  src/components/forms/DiskSizeSelector.tsx
  src/context/loadCustomVolumes.tsx
  src/context/loadIsoVolumes.tsx
  src/context/useStoragePools.tsx
  src/context/useVolumes.tsx
  src/pages/images/CustomIsoSelector.tsx
  src/pages/instances/forms/CreateInstanceFromSnapshotForm.tsx
  src/pages/instances/forms/DuplicateInstanceForm.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/StoragePoolDetail.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/StorageVolumeDetail.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/actions/CreateStoragePoolBtn.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/forms/ClusteredSourceSelector.tsx
  src/pages/storage/forms/ClusteredZfsNameSelector.tsx
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/types/storage.d.ts
  src/util/configInheritance.spec.ts
  src/util/configInheritance.tsx
  src/util/entitlements/server.tsx
  src/util/entitlements/storage-pools.tsx
  src/util/formChangeCount.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Code +1, Review: QA +1

#1121 feat: increase number of retrys and duration of delay for loading the UI
  src/util/lazyWithRetry.tsx
Labels: Review: Code +1

#1119 feat: restricted permissions for project edit page
  src/api/projects.tsx
  src/context/auth.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/projects/ProjectSelector.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/projects/forms/ProjectDetailsForm.tsx
  src/util/entitlements/projects.tsx
  src/util/entitlements/server.tsx
  src/util/projectEdit.tsx
Labels: Review: Code +1, Review: QA +1

#1120 feat: [WD-19338] Custom ISO Permission checks
  src/pages/images/actions/UploadCustomIsoBtn.tsx
  src/pages/storage/CustomIsoList.tsx
Labels: Review: Code +1, Review: QA +1

#1122 Permissions ux improvements
  src/pages/permissions/panels/GroupSelection.tsx
  src/types/permissions.d.ts
  src/util/helpers.tsx
Labels: Review: Code +1, Review: QA +1

#1113 feat: restricted permissions for permission management [WD-18906]
  src/api/auth-groups.tsx
  src/api/auth-identities.tsx
  src/api/auth-idp-groups.tsx
  src/components/SelectableMainTable.tsx
  src/context/useGroups.tsx
  src/context/useIdentities.tsx
  src/context/useIdpGroups.tsx
  src/context/useLoggedInUser.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/images/ImageList.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/permissions/CreateTlsIdentityBtn.tsx
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/PermissionIdpGroups.tsx
  src/pages/permissions/actions/BulkDeleteGroupsBtn.tsx
  src/pages/permissions/actions/BulkDeleteIdentitiesBtn.tsx
  src/pages/permissions/actions/BulkDeleteIdpGroupsBtn.tsx
  src/pages/permissions/actions/DeleteGroupModal.tsx
  src/pages/permissions/actions/DeleteIdentityBtn.tsx
  src/pages/permissions/actions/DeleteIdpGroupBtn.tsx
  src/pages/permissions/actions/DeleteIdpGroupsModal.tsx
  src/pages/permissions/actions/EditIdentityGroupsBtn.tsx
  src/pages/permissions/actions/GroupActions.tsx
  src/pages/permissions/forms/GroupForm.tsx
  src/pages/permissions/panels/CreateIdpGroupPanel.tsx
  src/pages/permissions/panels/EditGroupIdentitiesPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/pages/permissions/panels/EditIdentitiesForm.tsx
  src/pages/permissions/panels/EditIdentityGroupsPanel.tsx
  src/pages/permissions/panels/EditIdpGroupPanel.tsx
  src/pages/permissions/panels/GroupSelection.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/sass/_selectable_main_table.scss
  src/types/permissions.d.ts
  src/util/entitlements/groups.tsx
  src/util/entitlements/identities.tsx
  src/util/entitlements/idp-groups.tsx
  src/util/entitlements/server.tsx
  src/util/permissionIdpGroups.tsx
Labels: Review: Code +1, Review: QA +1

#1123 feat: generalise bulk delete button across UI pages [WD-19546]
  src/components/BulkDeleteButton.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/actions/BulkDeleteImageBtn.tsx
  src/pages/instances/actions/InstanceBulkDelete.tsx
  src/pages/instances/actions/snapshots/InstanceSnapshotBulkDelete.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/actions/BulkDeleteGroupsBtn.tsx
  src/pages/permissions/actions/BulkDeleteIdentitiesBtn.tsx
  src/pages/permissions/actions/BulkDeleteIdpGroupsBtn.tsx
  src/pages/permissions/actions/DeleteGroupModal.tsx
  src/pages/storage/actions/snapshots/VolumeSnapshotBulkDelete.tsx
  tests/permission-groups.spec.ts
  tests/permission-idp-groups.spec.ts
Labels: Review: Code +1, Review: QA +1

#1129 feat: [WD-19698] Custom ISO can_delete permission check.
  src/api/storage-pools.tsx
  src/api/storage-volumes.tsx
  src/context/loadIsoVolumes.tsx
  src/context/useVolumes.tsx
  src/pages/storage/CustomVolumeCreateModal.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/StorageVolumeSize.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/pages/storage/actions/DeleteStorageVolumeBtn.tsx
  src/pages/storage/actions/snapshots/VolumeConfigureSnapshotModal.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
  src/pages/storage/forms/DuplicateVolumeForm.tsx
  src/pages/storage/forms/EditStorageVolume.tsx
  src/types/storage.d.ts
  src/util/entitlements/storage-volumes.tsx
Labels: Review: Code +1, Review: QA +1

#1127 Allow member specific server setting for core.syslog_server WD-18265
  src/components/ClusterSpecificSelect.tsx
  src/components/forms/ClusterSpecificInput.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/settings/ClusteredSettingFormInput.tsx
  src/pages/settings/SettingForm.tsx
  src/pages/settings/Settings.tsx
  src/sass/_settings_page.scss
Labels: Review: Code needed, Review: QA needed
