Repository canonical/lxd-ui, pull requests merged in 2025-09, with the labels that each got.

#1444 feat: [WD-24077] Enable clustering tests + workflow integration
  .github/workflows/pr.yaml
  package.json
  playwright.config.ts
  tests/enable-clustering.spec.ts
  tests/groups-clustered.spec.ts
  tests/helpers/cluster.ts
  tests/helpers/instances.ts
  tests/helpers/storageVolume.ts
  tests/instances.spec.ts
  tests/members-clustered.spec.ts
  tests/projects-clustered.spec.ts
  tests/projects.spec.ts
Labels: Review: Code needed

#1476 fix(doc-test) instance scriplet link got removed from the doc helptext
  tests/doc-links.spec.ts
Labels: Review: Code needed

#1473 feat(microcloud) add favicon if under microcloud
  public/assets/img/microCloud-32x32.png
  src/App.tsx
  src/util/favicon.tsx
  src/util/title.tsx
Labels: Review: Code +1, Review: QA +1

#1470 feat: [WD-26013] Hide acknowledged warnings by default
  src/components/Navigation.tsx
  src/pages/warnings/WarningList.tsx
  src/pages/warnings/WarningSearchFilter.tsx
  src/types/warning.d.ts
  src/util/warningFilter.tsx
Labels: Review: Code needed, Review: QA needed

#1482 feat(InstanceList, InstanceIps): sort IPv6 addresses in InstanceIps and display 2 IPv6 addresses in InstanceList (+n more if necessary)
  src/pages/instances/InstanceIps.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceListIps.tsx
  src/types/instance.d.ts
  src/util/networks.spec.ts
  src/util/networks.tsx
Labels: Review: Code needed, Review: QA needed

#1495 fix: Minor reuse variables related to HPE drivers.
  src/util/storagePool.tsx
Labels: Review: QA needed

#1498 Wd 26612 fix label lts
  src/pages/images/ImageSelector.tsx
  src/pages/instances/forms/InstanceCreateDetailsForm.tsx
  src/sass/_forms.scss
  src/util/images.tsx
Labels: Review: Code needed, Review: QA needed

#1448 feat: [WD-24083] Run low permissions tests in github
  tests/helpers/instances.ts
  tests/helpers/permissions.ts
  tests/instances.spec.ts
  tests/permissions-read-only.spec.ts
Labels: Review: Code +1

#1506 fix(instance) column responsiveness for a non-clustered environment for the instance list should not consider cluster member column
  src/pages/instances/InstanceList.tsx
Labels: Review: Code +1, Review: QA +1

#1503 feat(instance) loading status for instances consistency update
  src/Root.tsx
  src/context/instanceLoading.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/actions/InstanceBulkAction.tsx
  src/pages/instances/actions/StopInstanceBtn.tsx
  src/util/mapsAreEqual.tsx
  src/util/operations.tsx
Labels: Review: Code +1, Review: QA +1

#1504 fix(permissions) idp group info should be without notification wrapper in empty state
  src/pages/permissions/PermissionIdpGroups.tsx
Labels: Review: Code +1, Review: QA +1

#1509 feat(instance) show notification on exporting instance with attached disks
  src/pages/instances/forms/ExportInstanceModal.tsx
Labels: Review: Code +1, Review: QA +1

#1505 fix(cluster) permission checks for cluster groups and members
  src/components/SelectableMainTable.tsx
  src/pages/cluster/ClusterGroupList.tsx
  src/pages/cluster/ClusterMemberList.tsx
  src/pages/cluster/actions/CreateClusterGroupBtn.tsx
  src/pages/cluster/actions/DeleteClusterGroupBtn.tsx
  src/pages/cluster/actions/EditClusterGroupBtn.tsx
  src/pages/cluster/actions/EditClusterMemberBtn.tsx
  src/pages/cluster/actions/EvacuateClusterMemberBtn.tsx
  src/pages/cluster/actions/RestoreClusterMemberBtn.tsx
  tests/helpers/cluster.ts
  tests/helpers/permission-groups.ts
  tests/helpers/permission-identities.ts
  tests/helpers/permission-idp-groups.ts
  tests/members-clustered.spec.ts
  tests/permissions-read-only.spec.ts
Labels: Review: Code needed, Review: QA +1

#1519 docs(CONTRIBUTING): Add Permissions section
  CONTRIBUTING.md
Labels: Docs +1
