Repository canonical/lxd-ui, pull requests merged in 2025-08, with the labels that each got.

#1416 feat(tests): [WD-24079] UI Tests for SRIOV and MacVLAN networks
  src/pages/networks/forms/NetworkGVRPField.tsx
  src/pages/networks/forms/NetworkMTUField.tsx
  src/pages/networks/forms/NetworkVlanField.tsx
  tests/helpers/network.ts
  tests/networks.spec.ts
Labels: Review: Code needed

#1425 Upstream scrollable components
  package.json
  src/components/ScrollableContainer.tsx
  src/components/ScrollableForm.tsx
  src/components/ScrollableTable.tsx
  src/components/forms/ScrollableConfigurationTable.tsx
  src/components/forms/SelectGPUModal.tsx
  src/pages/cluster/ClusterGroupList.tsx
  src/pages/cluster/ClusterMemberHardware.tsx
  src/pages/cluster/ClusterMemberList.tsx
  src/pages/cluster/ClusterMemberSelectTable.tsx
  src/pages/cluster/panels/CreateClusterGroupPanel.tsx
  src/pages/cluster/panels/EditClusterGroupPanel.tsx
  src/pages/cluster/panels/EditClusterMemberPanel.tsx
  src/pages/images/ImageList.tsx
  src/pages/images/ImageSelector.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceSnapshots.tsx
  src/pages/networks/NetworkForwards.tsx
  src/pages/networks/NetworkIPAM.tsx
  src/pages/networks/NetworkLeases.tsx
  src/pages/networks/forms/NetworkAclForm.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/operations/OperationList.tsx
  src/pages/permissions/PermissionGroups.tsx
  src/pages/permissions/PermissionIdentities.tsx
  src/pages/permissions/PermissionIdpGroups.tsx
  src/pages/permissions/panels/CreateGroupPanel.tsx
  src/pages/permissions/panels/EditGroupIdentitiesPanel.tsx
  src/pages/permissions/panels/EditGroupPanel.tsx
  src/pages/permissions/panels/EditGroupPermissionsForm.tsx
  src/pages/permissions/panels/EditIdentitiesForm.tsx
  src/pages/permissions/panels/GroupSelection.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/projects/ProjectSelectTable.tsx
  src/pages/settings/Settings.tsx
  src/pages/storage/CustomIsoList.tsx
  src/pages/storage/CustomVolumeSelectModal.tsx
  src/pages/storage/StorageBucketKeys.tsx
  src/pages/storage/StorageBuckets.tsx
  src/pages/storage/StoragePoolSelectTable.tsx
  src/pages/storage/StoragePools.tsx
  src/pages/storage/StorageVolumeSnapshots.tsx
  src/pages/storage/StorageVolumes.tsx
  src/pages/storage/panels/CreateStorageBucketKeyPanel.tsx
  src/pages/storage/panels/CreateStorageBucketPanel.tsx
  src/pages/storage/panels/EditStorageBucketKeyPanel.tsx
  src/pages/storage/panels/EditStorageBucketPanel.tsx
  src/pages/warnings/WarningList.tsx
  src/sass/_scrollable_container.scss
  src/sass/_scrollable_table.scss
  src/sass/styles.scss
  src/util/helpers.tsx
  src/util/updateMaxHeight.tsx
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#1434 fix(scss) ensure our scsss settings are used in react components scss
  src/sass/_settings.scss
  vite.config.ts
Labels: Review: Code +1, Review: QA +1

#1435 fix: [WD-25626] Add content headers to Storage buckets
  src/api/storage-buckets.tsx
Labels: Review: Code +1, Review: QA +1

#1436 fix(caching) settings and documentation objects files can be considered fresh in cache for up to 1 minute
  src/context/useSettings.tsx
  src/pages/settings/ConfigFieldDescription.tsx
Labels: Review: Code needed

#1443 fix(forms) ensure forms calculate the right height for configuration tables
  src/components/forms/FormFooterLayout.tsx
  src/sass/_forms.scss
Labels: Review: Code needed

#1423 chore(test) make instance terminal test more resilient
  tests/instances.spec.ts
Labels: Review: Code needed

#1445 fix(cluster) enable clustering permission handling should not always disable the button
  src/pages/cluster/actions/EnableClusteringBtn.tsx
Labels: Review: Code +1, Review: QA +1

#1449 feat(auth): permissions are not fine-grained with unix authentication
  src/components/Navigation.tsx
  src/context/auth.tsx
  src/context/useLoggedInUser.tsx
  src/pages/instances/Events.tsx
  src/pages/instances/InstanceGraphicConsole.tsx
  src/pages/instances/InstanceTerminal.tsx
  src/pages/instances/InstanceTextConsole.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
Labels: Review: Code needed
