Repository canonical/lxd-ui, pull requests merged in 2025-01, with the labels that each got.

#1037 Avoid duplicate title setting from resource label and the table cell in identities list
  src/pages/permissions/PermissionIdentities.tsx
Labels: Review: Code +1, Review: QA +1

#1046 Avoid null pointer exception in storage pools.
  src/pages/storage/StorageVolumeSize.tsx
  src/types/storage.d.ts
  src/util/storagePoolForm.tsx
Labels: Review: Code +1, Review: QA +1

#1043 Link idp group count to edit panel
  src/pages/permissions/PermissionIdpGroups.tsx
Labels: Review: Code +1, Review: QA +1

#1042 Do not limit length when using resource link is use in the main section
  src/sass/_resources.scss
Labels: Review: Code +1, Review: QA +1

#1045 chore(deps) update dependencies
  .eslintignore
  .eslintrc.cjs
  eslint.config.mjs
  package.json
  src/components/ConfigurationRow.tsx
  src/components/ErrorBoundary.tsx
  src/components/TabLinks.tsx
  src/pages/cluster/ClusterGroupForm.tsx
  src/pages/cluster/actions/DeleteClusterGroupBtn.tsx
  src/pages/images/actions/CreateInstanceFromImageBtn.tsx
  src/pages/instances/CreateInstance.tsx
  src/pages/instances/EditInstance.tsx
  src/pages/instances/InstanceDetailHeader.tsx
  src/pages/instances/InstanceGraphicConsole.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/actions/DeleteInstanceBtn.tsx
  src/pages/instances/actions/OpenConsoleBtn.tsx
  src/pages/instances/actions/OpenTerminalBtn.tsx
  src/pages/instances/forms/UploadExternalFormatFileForm.tsx
  src/pages/instances/forms/UploadInstanceBackupFileForm.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/NetworkDetailHeader.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/NetworkMap.tsx
  src/pages/networks/actions/DeleteNetworkBtn.tsx
  src/pages/profiles/CreateProfile.tsx
  src/pages/profiles/EditProfile.tsx
  src/pages/profiles/ProfileDetailHeader.tsx
  src/pages/profiles/ProfileList.tsx
  src/pages/profiles/actions/DeleteProfileBtn.tsx
  src/pages/projects/CreateProject.tsx
  src/pages/projects/EditProject.tsx
  src/pages/projects/ProjectConfigurationHeader.tsx
  src/pages/projects/actions/DeleteProjectBtn.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/MigrateVolumeBtn.tsx
  src/pages/storage/StoragePoolHeader.tsx
  src/pages/storage/StorageVolumeHeader.tsx
  src/pages/storage/actions/CreateVolumeBtn.tsx
  src/pages/storage/actions/CustomIsoBtn.tsx
  src/pages/storage/actions/DeleteStoragePoolBtn.tsx
  src/pages/storage/actions/StorageVolumesInPoolBtn.tsx
  src/pages/storage/forms/CreateStorageVolume.tsx
  src/pages/storage/forms/EditStorageVolume.tsx
  src/util/helpers.tsx
  tests/helpers/configuration.ts
  tests/helpers/images.ts
  tests/helpers/instances.ts
  tests/helpers/network.ts
  tests/helpers/profile.ts
  tests/helpers/storagePool.ts
  tests/helpers/storageVolume.ts
  tests/images.spec.ts
  tests/instances.spec.ts
  vite.config.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1050 Rectify link to for operation status
  src/components/OperationStatus.tsx
Labels: Review: Code +1, Review: QA +1

#1035 Overhaul network layout
  src/components/ConfigurationRow.tsx
  src/components/UsedByItem.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkDetailOverview.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/NetworkTopology.tsx
  src/pages/networks/forms/IpAddress.tsx
  src/pages/networks/forms/IpAddressSelector.tsx
  src/pages/networks/forms/NetworkAddresses.tsx
  src/pages/networks/forms/NetworkDescriptionField.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormBridge.tsx
  src/pages/networks/forms/NetworkFormDns.tsx
  src/pages/networks/forms/NetworkFormIpv4.tsx
  src/pages/networks/forms/NetworkFormIpv6.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkFormMenu.tsx
  src/pages/networks/forms/NetworkFormOvn.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/NetworkProfiles.tsx
  src/pages/networks/forms/NetworkStatistics.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/pages/profiles/ProfileList.tsx
  src/sass/_forms.scss
  src/sass/_ip_address.scss
  src/sass/_network_detail_overview.scss
  src/sass/_network_form.scss
  src/sass/_network_topology.scss
  src/sass/_profile_list.scss
  src/sass/styles.scss
  src/util/debounce.tsx
  src/util/networks.tsx
  src/util/scroll.tsx
  tests/helpers/network.ts
  tests/networks.spec.ts
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#1054 feat: use custom select component from react-components
  src/components/select/CustomSelect.tsx
  src/components/select/CustomSelectDropdown.tsx
  src/pages/permissions/panels/PermissionSelector.tsx
  src/pages/storage/StoragePoolSelector.tsx
  src/sass/_custom_select.scss
  src/sass/styles.scss
  src/util/customSelect.spec.ts
  src/util/customSelect.tsx
  src/util/permissions.tsx
Labels: Review: Code needed, Review: QA needed

#1059 fix: fix broken doc link e2e test
  tests/doc-links.spec.ts
Labels: Review: Code needed

#1058 fix: remove spaces from custom iso name
  src/components/forms/SnapshotForm.tsx
  src/pages/storage/UploadCustomIso.tsx
  src/sass/_custom_isos.scss
  src/sass/_snapshots.scss
  src/util/customISO.tsx
  src/util/instanceSnapshots.tsx
  src/util/storageVolumeSnapshots.tsx
Labels: Review: Code +1, Review: QA +1

#1047 feat: [WD-17984] Add Pure Storage
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/pages/storage/forms/StoragePoolFormMenu.tsx
  src/pages/storage/forms/StorageVolumeForm.tsx
  src/types/config.d.ts
  src/util/permissions.spec.ts
  src/util/storageOptions.tsx
  src/util/storagePool.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#1060 chore: make vite dev server port configurable
  .env
  .github/workflows/coverage.yaml
  .github/workflows/pr.yaml
  CONTRIBUTING.md
  entrypoint
  haproxy-demo.cfg
  haproxy-dev.cfg
  package.json
  vite.config.ts
Labels: Review: Code +1, Review: QA +1

#943 Add links to grafana from instance detail pages, add grafana provision script
  public/assets/scripts/setup-grafana.sh
  src/pages/instances/InstanceDetail.tsx
  src/pages/settings/Settings.tsx
  tests/server.spec.ts
Labels: Review: Code +1, Review: QA +1

#1053 Network clustering
  package.json
  src/App.tsx
  src/api/networks.tsx
  src/components/ClusterSpecificSelect.tsx
  src/components/FormEditButton.tsx
  src/components/RenameHeader.tsx
  src/components/forms/NetworkDevicesForm.tsx
  src/pages/networks/CreateNetwork.tsx
  src/pages/networks/CreateNetworkForward.tsx
  src/pages/networks/EditNetwork.tsx
  src/pages/networks/EditNetworkForward.tsx
  src/pages/networks/MapLegend.tsx
  src/pages/networks/MapTooltip.tsx
  src/pages/networks/NetworkClusterMemberChip.tsx
  src/pages/networks/NetworkDetail.tsx
  src/pages/networks/NetworkDetailHeader.tsx
  src/pages/networks/NetworkForwardCount.tsx
  src/pages/networks/NetworkList.tsx
  src/pages/networks/NetworkMap.tsx
  src/pages/networks/NetworkSearchFilter.tsx
  src/pages/networks/NetworkTopology.tsx
  src/pages/networks/forms/NetworkAddresses.tsx
  src/pages/networks/forms/NetworkForm.tsx
  src/pages/networks/forms/NetworkFormMain.tsx
  src/pages/networks/forms/NetworkParentSelector.tsx
  src/pages/networks/forms/NetworkStatistics.tsx
  src/pages/networks/forms/NetworkTypeSelector.tsx
  src/pages/networks/forms/UplinkSelector.tsx
  src/sass/_cluster_specific_input.scss
  src/sass/_network_list.scss
  src/sass/_network_map.scss
  src/sass/_network_topology.scss
  src/sass/styles.scss
  src/types/network.d.ts
  src/util/intersection.spec.ts
  src/util/intersection.tsx
  src/util/networkForm.tsx
  yarn.lock
Labels: Review: Design +1, Review: Code +1, Review: QA +1

#1072 Ensure unique keys on the network list
  src/pages/networks/NetworkList.tsx
Labels: Review: Code +1, Review: QA +1

#1073 Show line and ... for an ovn network that has an uplink with parent next to it to indicate further level of detail
  src/pages/networks/NetworkTopology.tsx
  src/sass/_network_topology.scss
Labels: Review: Code needed, Review: QA needed

#1070 feat: [WD-18264] CMS fields for storage pool source
  src/api/networks.tsx
  src/api/storage-pools.tsx
  src/components/forms/ClusterSpecificInput.tsx
  src/pages/storage/CreateStoragePool.tsx
  src/pages/storage/EditStoragePool.tsx
  src/pages/storage/forms/StoragePoolClusteredSourceSelector.tsx
  src/pages/storage/forms/StoragePoolForm.tsx
  src/pages/storage/forms/StoragePoolFormMain.tsx
  src/sass/_cluster_specific_input.scss
  src/types/storage.d.ts
  src/util/helpers.tsx
  src/util/storageOptions.tsx
  src/util/storagePoolForm.tsx
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#1075 Show cpu and disk usage in instance list. distinguish memory cached and used
  src/components/Meter.tsx
  src/pages/instances/InstanceDisk.tsx
  src/pages/instances/InstanceList.tsx
  src/pages/instances/InstanceOverviewMetrics.tsx
  src/pages/instances/InstanceUsageMemory.tsx
  src/sass/_meter.scss
  src/util/instanceTable.tsx
  src/util/metricSelectors.tsx
Labels: Review: Code +1, Review: QA +1

#1076 Close side panel if panel instance was deleted
  src/pages/instances/InstanceList.tsx
Labels: Review: Code needed, Review: QA needed

#1079 Add cluster.evacuate as instance and profile configuration
  src/components/forms/MigrationForm.tsx
  src/util/instanceConfigFields.tsx
  src/util/instanceEdit.tsx
  src/util/instanceOptions.tsx
  tests/iso-volumes.spec.ts
Labels: Review: Code +1, Review: QA +1
